const Q = (stem, options, answer, explanation) => ({ stem, options, answer, explanation });

export const TOPICS_L3 = {
  reflexive: {
    key: 'engReflexive', label: '反身代词', icon: '🪞',
    color: '#338F9B', bg: '#E4F2F3', desc: 'myself / yourself',
  },
  indefinite: {
    key: 'engIndef', label: '不定代词', icon: '🎲',
    color: '#7BAE8E', bg: '#EDF5F0', desc: 'some / any / every',
  },
  relative: {
    key: 'engRelative', label: '关系代词', icon: '🔗',
    color: '#EB9F4A', bg: '#FDF3E4', desc: 'who / which / that',
  },
  wordForm: {
    key: 'engWordForm', label: '构词法', icon: '🧩',
    color: '#9B7EBD', bg: '#F0EBF5', desc: 'un- / -ful / -less',
  },
  pastFuture: {
    key: 'engPastFut', label: '过去时和将来时', icon: '⏳',
    color: '#D4839A', bg: '#F8ECF0', desc: 'did / will + do',
  },
  perfect: {
    key: 'engPerfect', label: '现在完成时', icon: '✅',
    color: '#5B8A9A', bg: '#E8EEF0', desc: 'have/has + done',
  },
  passive: {
    key: 'engPassive', label: '被动语态', icon: '🔄',
    color: '#E08B5A', bg: '#FDF0E6', desc: 'be + done',
  },
  agreement: {
    key: 'engAgreement', label: '主谓一致', icon: '🤝',
    color: '#8BA67A', bg: '#EEF3EB', desc: '主语决定谓语形式',
  },
  attrClause: {
    key: 'engAttrClause', label: '定语从句', icon: '📎',
    color: '#A0856E', bg: '#F3EDE6', desc: 'the boy who...',
  },
  subjunctive: {
    key: 'engSubjunctive', label: '虚拟语气和特殊句式', icon: '💭',
    color: '#7E9BAE', bg: '#E8EFF3', desc: 'If I were... / So do I',
  },
};

export const LEARN_L3 = {
  reflexive: [
    { title: '什么是反身代词？', emoji: '🪞', body: '反身代词表示"自己"，强调动作回到主语自身。', highlight: '...self(单数) / ...selves(复数)', examples: [] },
    { title: '反身代词表', emoji: '📋', body: 'I → myself     you → yourself\nhe → himself    she → herself\nit → itself     we → ourselves\nyou(复) → yourselves\nthey → themselves', highlight: '单数 -self，复数 -selves', examples: [{ en: 'I can do it myself.', zh: '我自己能做。' }, { en: 'She looked at herself in the mirror.', zh: '她看着镜子中的自己。' }] },
    { title: '用法', emoji: '💡', body: '1. 做宾语：主语和宾语是同一人\n2. 做强调：亲自做某事\n\nHelp yourself! = 请自便！\nby oneself = 独自地', highlight: 'Help yourself / by myself', examples: [{ en: 'He hurt himself.', zh: '他伤到了自己。' }, { en: 'I finished it by myself.', zh: '我独自完成的。' }] },
  ],
  indefinite: [
    { title: '不定代词家族', emoji: '🎲', body: '不定代词指不确定的人或物。\nsome-, any-, every-, no- 开头：', highlight: 'some / any / every / no + thing/one/where', examples: [] },
    { title: 'some 系列', emoji: '✅', body: 'someone 某人  something 某物\nsomewhere 某处\n\n一般用于肯定句。', highlight: 'some → 肯定句', examples: [{ en: 'Someone is at the door.', zh: '有人在门口。' }, { en: 'I want something to eat.', zh: '我想吃点东西。' }] },
    { title: 'any 系列', emoji: '❓', body: 'anyone 任何人  anything 任何事\nanywhere 任何地方\n\n一般用于否定句和疑问句。', highlight: 'any → 否定句/疑问句', examples: [{ en: 'Is there anyone here?', zh: '这里有人吗？' }, { en: 'I don\'t have anything.', zh: '我什么都没有。' }] },
    { title: 'every 和 no', emoji: '💡', body: 'everyone/everybody 每个人\neverything 一切  everywhere 到处\n\nnobody/no one 没有人\nnothing 没有东西  nowhere 没有地方', highlight: 'every = 全部, no = 没有', examples: [{ en: 'Everyone is here.', zh: '每个人都在。' }, { en: 'Nothing is impossible.', zh: '没有什么不可能。' }] },
  ],
  relative: [
    { title: '关系代词入门', emoji: '🔗', body: '关系代词用来连接两个句子，修饰前面的名词。\n像一个钩子把两个句子挂在一起。', highlight: 'who / which / that 引导定语从句', examples: [] },
    { title: 'who = 修饰人', emoji: '👤', body: 'who 用在先行词是人的时候', highlight: '先行词是人 → who', examples: [{ en: 'The boy who is singing is Tom.', zh: '正在唱歌的男孩是Tom。' }, { en: 'I know the girl who won the prize.', zh: '我认识那个获奖的女孩。' }] },
    { title: 'which = 修饰物', emoji: '📦', body: 'which 用在先行词是物的时候', highlight: '先行词是物 → which', examples: [{ en: 'The book which I read is good.', zh: '我读的那本书很好。' }, { en: 'The cat which is sleeping is mine.', zh: '正在睡觉的猫是我的。' }] },
    { title: 'that = 万能替换', emoji: '💡', body: 'that 既可以修饰人也可以修饰物。\n在口语中最常用！', highlight: 'that 可以替代 who 和 which', examples: [{ en: 'The man that helped me is kind.', zh: '帮助我的那个人很善良。' }, { en: 'The pen that I lost is red.', zh: '我丢的那支笔是红色的。' }] },
  ],
  wordForm: [
    { title: '什么是构词法？', emoji: '🧩', body: '通过加前缀或后缀来创造新词。\n就像拼积木一样！', highlight: '前缀改变意思，后缀改变词性', examples: [] },
    { title: '常用前缀', emoji: '🔧', body: 'un- = 不（反义）: happy → unhappy\nre- = 再/重新: write → rewrite\ndis- = 不/去掉: like → dislike', highlight: '前缀加在词前面', examples: [{ en: 'He is unhappy today.', zh: '他今天不开心。' }, { en: 'Please rewrite this sentence.', zh: '请重写这个句子。' }] },
    { title: '常用后缀', emoji: '🔩', body: '-ful = 充满的: care → careful\n-less = 没有的: care → careless\n-er = 做…的人: teach → teacher\n-ly = 变副词: quick → quickly', highlight: '后缀加在词后面', examples: [{ en: 'She is a careful girl.', zh: '她是个细心的女孩。' }, { en: 'He is a careless boy.', zh: '他是个粗心的男孩。' }] },
    { title: '对比记忆', emoji: '💡', body: '-ful ↔ -less 是反义后缀：\nhopeful 充满希望 ↔ hopeless 没有希望\nuseful 有用 ↔ useless 没用\ncolorful 多彩 ↔ colorless 无色', highlight: '-ful 有… / -less 没有…', examples: [] },
  ],
  pastFuture: [
    { title: '一般过去时', emoji: '⏪', body: '表示过去发生的事。\n动词变过去式。', highlight: '过去的事 → 动词过去式', examples: [{ en: 'I went to school yesterday.', zh: '我昨天去了学校。' }, { en: 'She played tennis last week.', zh: '她上周打了网球。' }] },
    { title: '过去式变化规则', emoji: '✏️', body: '一般加 -ed: played, walked\n以e结尾加 -d: liked, danced\n辅音+y → ied: studied, carried\n不规则: go→went, eat→ate, see→saw', highlight: '大部分+ed，少数不规则', examples: [{ en: 'He watched a movie.', zh: '他看了一部电影。' }] },
    { title: '一般将来时', emoji: '⏩', body: '表示将来要做的事。\nwill + 动词原形\nbe going to + 动词原形', highlight: '将来 → will / be going to', examples: [{ en: 'I will help you.', zh: '我会帮你的。' }, { en: 'She is going to visit her grandma.', zh: '她打算去看奶奶。' }] },
    { title: '否定和疑问', emoji: '❓', body: '过去时: didn\'t + 动词原形\n将来时: won\'t + 动词原形\n\n疑问: Did you...? / Will you...?', highlight: '有了 did/will 动词回原形！', examples: [{ en: 'I didn\'t see him.', zh: '我没有看到他。' }, { en: 'Will you come tomorrow?', zh: '你明天来吗？' }] },
  ],
  perfect: [
    { title: '什么是现在完成时？', emoji: '✅', body: '表示过去的动作对现在有影响。\nhave/has + 过去分词 (done)', highlight: 'have/has + done', examples: [] },
    { title: 'have vs has', emoji: '📋', body: 'I/you/we/they → have\nhe/she/it → has', highlight: '三单用 has，其他用 have', examples: [{ en: 'I have finished my homework.', zh: '我已经做完作业了。' }, { en: 'She has gone to Beijing.', zh: '她已经去了北京。' }] },
    { title: '常见过去分词', emoji: '📝', body: '规则: play→played, like→liked\n不规则: go→gone, eat→eaten\nsee→seen, write→written\ndo→done, be→been', highlight: '过去分词需要记忆', examples: [{ en: 'Have you eaten lunch?', zh: '你吃午饭了吗？' }] },
    { title: '标志词', emoji: '💡', body: 'already 已经  yet 还（没）\njust 刚刚  ever 曾经  never 从不\nsince 自从  for 持续了', highlight: '看到这些词想到完成时！', examples: [{ en: 'I have already done it.', zh: '我已经做了。' }, { en: 'He has lived here for 5 years.', zh: '他在这住了5年。' }] },
  ],
  passive: [
    { title: '什么是被动语态？', emoji: '🔄', body: '当主语是动作的承受者时，用被动语态。\n格式: be + 过去分词', highlight: '主语被...→被动语态', examples: [] },
    { title: '构成方式', emoji: '📋', body: '一般现在时: am/is/are + done\n一般过去时: was/were + done\n\n主动 → 被动：\nI clean the room.\n→ The room is cleaned.', highlight: 'be + 过去分词', examples: [{ en: 'The window was broken.', zh: '窗户被打破了。' }, { en: 'English is spoken in many countries.', zh: '很多国家说英语。' }] },
    { title: 'by + 执行者', emoji: '👉', body: '如果要说明是谁做的，用 by。', highlight: 'be + done + by + 执行者', examples: [{ en: 'The cake was made by Mom.', zh: '蛋糕是妈妈做的。' }, { en: 'The book was written by Rowling.', zh: '这本书是Rowling写的。' }] },
  ],
  agreement: [
    { title: '主谓一致', emoji: '🤝', body: '主语和谓语的单复数要一致！\n单数主语 + 单数谓语\n复数主语 + 复数谓语', highlight: '主语决定谓语的形式', examples: [] },
    { title: '基本规则', emoji: '📋', body: 'He runs. (单数)\nThey run. (复数)\nThe dog is cute. (单数)\nThe dogs are cute. (复数)', highlight: '一个→is/has/does，多个→are/have/do', examples: [{ en: 'She goes to school.', zh: '她上学。' }, { en: 'They go to school.', zh: '他们上学。' }] },
    { title: '特殊情况', emoji: '⚡', body: 'everyone/everybody → 单数\nthe + 形容词（表一类人） → 复数\nand 连接两主语 → 复数\nor 连接 → 就近原则', highlight: 'everyone = 单数！and = 复数！', examples: [{ en: 'Everyone is here.', zh: '每个人都在。' }, { en: 'Tom and Jerry are friends.', zh: 'Tom和Jerry是朋友。' }] },
    { title: '不可数名词', emoji: '💡', body: '不可数名词做主语 → 单数谓语\nwater, money, news 等', highlight: '不可数 = 单数', examples: [{ en: 'The news is good.', zh: '这消息是好的。' }, { en: 'Water is important.', zh: '水很重要。' }] },
  ],
  attrClause: [
    { title: '什么是定语从句？', emoji: '📎', body: '定语从句用来修饰名词，\n告诉我们"哪一个"。\n被修饰的词叫先行词。', highlight: '先行词 + 关系词 + 从句', examples: [] },
    { title: '引导词选择', emoji: '🔍', body: '先行词是人 → who/that\n先行词是物 → which/that\n表示所属 → whose', highlight: '人用who，物用which，都可用that', examples: [{ en: 'The girl who is dancing is Amy.', zh: '正在跳舞的女孩是Amy。' }, { en: 'The book which I bought is great.', zh: '我买的那本书很棒。' }] },
    { title: '关系词做成分', emoji: '📋', body: '关系词在从句中做主语或宾语：\n做主语: The boy who likes music (who做主语)\n做宾语: The pen (that) I lost (that做宾语，可省)', highlight: '做宾语时 that/which 可省略', examples: [{ en: 'I like the cake (that) you made.', zh: '我喜欢你做的蛋糕。' }] },
    { title: '常用句型', emoji: '💡', body: 'The man who is wearing... 穿着…的人\nThe thing that I like most... 我最喜欢的东西\nThe place where we met... 我们见面的地方', highlight: '定语从句让描述更具体！', examples: [{ en: 'This is the place where I was born.', zh: '这是我出生的地方。' }] },
  ],
  subjunctive: [
    { title: '虚拟语气', emoji: '💭', body: '虚拟语气表示假设、愿望等非真实情况。\nIf + 过去式 → would + 动词原形', highlight: '假设用虚拟语气', examples: [{ en: 'If I were a bird, I would fly.', zh: '如果我是鸟，我就飞。' }] },
    { title: '倒装句', emoji: '🔃', body: 'So do I. = 我也是。\nNeither do I. = 我也不。\n\n用来快速表示"也"。', highlight: 'So/Neither + 助动词 + 主语', examples: [{ en: 'I like apples. — So do I.', zh: '我喜欢苹果。我也是。' }, { en: 'I can\'t swim. — Neither can I.', zh: '我不会游泳。我也不会。' }] },
    { title: 'There be 句型', emoji: '🏠', body: 'There is + 单数/不可数\nThere are + 复数\n\n表示"某处有某物"', highlight: 'There be 就近原则', examples: [{ en: 'There is a pen and two books.', zh: '有一支笔和两本书。' }] },
    { title: 'It 做形式主语', emoji: '💡', body: 'It is + adj + to do sth\n把真正的主语放后面，\n用 it 做形式主语。', highlight: 'It is easy to learn English.', examples: [{ en: 'It is important to be kind.', zh: '善良是重要的。' }, { en: 'It is fun to play games.', zh: '玩游戏很有趣。' }] },
  ],
};

export const QUESTIONS_L3 = {
  reflexive: [
    Q('I can do it ___. (我自己)', ['myself', 'yourself', 'herself', 'itself'], 0, '我自己→myself'),
    Q('She looked at ___ in the mirror.', ['himself', 'myself', 'herself', 'itself'], 2, '她自己→herself'),
    Q('He hurt ___. (他自己)', ['myself', 'herself', 'himself', 'yourself'], 2, '他自己→himself'),
    Q('Help ___! (请自便)', ['myself', 'yourself', 'himself', 'herself'], 1, 'Help yourself!'),
    Q('They enjoyed ___ at the party.', ['ourselves', 'myself', 'themselves', 'herself'], 2, '他们自己→themselves'),
    Q('We should believe in ___.', ['ourselves', 'myself', 'themselves', 'yourselves'], 0, '我们自己→ourselves'),
    Q('The cat cleaned ___.', ['himself', 'herself', 'itself', 'myself'], 2, '动物→itself'),
    Q('Did you finish it by ___?', ['myself', 'yourself', 'himself', 'herself'], 1, '你独自→by yourself'),
    Q('Be careful! Don\'t hurt ___!', ['myself', 'himself', 'yourself', 'herself'], 2, '(对你说)→yourself'),
    Q('I taught ___ to swim.', ['myself', 'yourself', 'himself', 'herself'], 0, '我自学→taught myself'),
    Q('She made ___ a dress.', ['himself', 'myself', 'herself', 'itself'], 2, '她给自己→herself'),
    Q('They need to do it ___.', ['ourselves', 'myself', 'themselves', 'yourself'], 2, '他们自己→themselves'),
    Q('Let me introduce ___. I\'m Tom.', ['myself', 'yourself', 'himself', 'herself'], 0, '自我介绍→myself'),
    Q('You two should behave ___.', ['yourself', 'yourselves', 'themselves', 'ourselves'], 1, '你们→yourselves'),
    Q('The baby can feed ___. (它自己)', ['himself', 'herself', 'myself', 'itself'], 3, '宝宝(不知性别)→itself'),
  ],
  indefinite: [
    Q('___ is at the door. (有人)', ['Someone', 'Anyone', 'No one', 'Everyone'], 0, '肯定句→Someone'),
    Q('Is there ___ in the room?', ['someone', 'anyone', 'no one', 'everyone'], 1, '疑问句→anyone'),
    Q('I don\'t have ___ to eat.', ['something', 'anything', 'nothing', 'everything'], 1, '否定句→anything'),
    Q('___ is ready for the test.', ['Someone', 'Anyone', 'No one', 'Everyone'], 3, '每个人→Everyone'),
    Q('There is ___ in the box. It\'s empty.', ['something', 'anything', 'nothing', 'everything'], 2, '空的→nothing'),
    Q('Would you like ___ to drink?', ['something', 'anything', 'nothing', 'everything'], 0, '建议用something'),
    Q('___ knows the answer. (没有人)', ['Someone', 'Anyone', 'Nobody', 'Everybody'], 2, '没有人→Nobody'),
    Q('I looked ___ but couldn\'t find it.', ['somewhere', 'anywhere', 'everywhere', 'nowhere'], 2, '到处→everywhere'),
    Q('Is ___ wrong? You look sad.', ['something', 'anything', 'nothing', 'everything'], 1, '疑问→anything'),
    Q('There isn\'t ___ I can do.', ['something', 'anything', 'nothing', 'everything'], 1, '否定→anything'),
    Q('___ wants ice cream! (每个人)', ['Someone', 'Anyone', 'Everyone', 'No one'], 2, '每个人→Everyone'),
    Q('Don\'t go ___. Stay here.', ['somewhere', 'anywhere', 'everywhere', 'nowhere'], 1, '否定→anywhere'),
    Q('I have ___ to tell you. (有件事)', ['something', 'anything', 'nothing', 'everything'], 0, '肯定→something'),
    Q('There is ___ new about the news.', ['something', 'anything', 'nothing', 'everything'], 2, '没有新消息→nothing'),
    Q('___ can do that. It\'s impossible.', ['Someone', 'Nobody', 'Everybody', 'Somebody'], 1, '没人能→Nobody'),
  ],
  relative: [
    Q('The boy ___ is reading is my brother.', ['which', 'who', 'what', 'where'], 1, '人→who'),
    Q('The book ___ I bought is interesting.', ['who', 'which', 'where', 'when'], 1, '物→which'),
    Q('She is the girl ___ won the prize.', ['which', 'what', 'who', 'where'], 2, '人→who'),
    Q('The movie ___ we watched was funny.', ['who', 'that', 'where', 'when'], 1, '物→that'),
    Q('I know the man ___ lives next door.', ['which', 'where', 'who', 'what'], 2, '人→who'),
    Q('The dress ___ she is wearing is nice.', ['who', 'which', 'where', 'when'], 1, '物→which'),
    Q('The dog ___ bit me ran away.', ['who', 'which', 'that', 'where'], 2, '动物→that/which'),
    Q('Is this the key ___ you lost?', ['who', 'where', 'that', 'when'], 2, '物→that'),
    Q('The teacher ___ teaches us is kind.', ['which', 'who', 'what', 'where'], 1, '人→who'),
    Q('The house ___ is red belongs to Tom.', ['who', 'which', 'what', 'where'], 1, '物→which'),
    Q('I have a friend ___ can speak French.', ['which', 'what', 'who', 'where'], 2, '人→who'),
    Q('The cake ___ Mom made is delicious.', ['who', 'that', 'where', 'when'], 1, '物→that'),
    Q('The girl ___ bag was stolen cried.', ['who', 'which', 'whose', 'that'], 2, '谁的→whose'),
    Q('This is the park ___ we play.', ['which', 'who', 'that', 'where'], 3, '地点→where'),
    Q('The song ___ she sang was beautiful.', ['who', 'that', 'where', 'when'], 1, '物→that'),
  ],
  wordForm: [
    Q('happy → ___ (反义)', ['rehappy', 'dishappy', 'unhappy', 'imhappy'], 2, 'un+happy=unhappy'),
    Q('care → ___ (充满关心的)', ['caring', 'careful', 'careless', 'cared'], 1, 'care+ful=careful'),
    Q('care → ___ (没有关心的)', ['caring', 'careful', 'careless', 'cared'], 2, 'care+less=careless'),
    Q('teach → ___ (教师)', ['teaching', 'teachful', 'teached', 'teacher'], 3, 'teach+er=teacher'),
    Q('quick → ___ (副词)', ['quicker', 'quickly', 'quickful', 'quickless'], 1, 'quick+ly=quickly'),
    Q('like → ___ (反义)', ['unlike', 'dislike', 'unwise', 'imlike'], 1, 'dis+like=dislike'),
    Q('use → ___ (有用的)', ['using', 'useless', 'useful', 'used'], 2, 'use+ful=useful'),
    Q('write → ___ (作家)', ['writing', 'writable', 'writer', 'written'], 2, 'write+r=writer'),
    Q('hope → ___ (充满希望的)', ['hoping', 'hopeful', 'hopeless', 'hoped'], 1, 'hope+ful=hopeful'),
    Q('kind → ___ (善良地)', ['kinder', 'kindest', 'kindly', 'kindful'], 2, 'kind+ly=kindly'),
    Q('possible → ___ (不可能的)', ['dispossible', 'unpossible', 'impossible', 'inpossible'], 2, 'im+possible'),
    Q('beauty → ___ (美丽的)', ['beautyful', 'beautiful', 'beautyless', 'beautied'], 1, 'beauty→beautiful'),
    Q('home → ___ (没有家的)', ['homeful', 'homeless', 'homeing', 'homed'], 1, 'home+less=homeless'),
    Q('read → ___ (读者)', ['reading', 'readable', 'reader', 'readed'], 2, 'read+er=reader'),
    Q('slow → ___ (副词)', ['slower', 'slowest', 'slowly', 'slowful'], 2, 'slow+ly=slowly'),
  ],
  pastFuture: [
    Q('I ___ (go) to the park yesterday.', ['go', 'went', 'going', 'gone'], 1, '过去→went'),
    Q('She ___ (eat) an apple last night.', ['eat', 'eats', 'ate', 'eaten'], 2, '过去→ate'),
    Q('They ___ (play) football last week.', ['play', 'plays', 'played', 'playing'], 2, '过去→played'),
    Q('I ___ help you tomorrow.', ['will', 'did', 'was', 'am'], 0, '将来→will'),
    Q('She ___ (not go) to school yesterday.', ['doesn\'t go', 'didn\'t go', 'won\'t go', 'isn\'t going'], 1, '过去否定→didn\'t'),
    Q('___ you ___ the movie? (see, past)', ['Did, see', 'Do, see', 'Will, see', 'Are, seeing'], 0, '过去疑问→Did you see'),
    Q('He ___ (study) hard last year.', ['study', 'studies', 'studied', 'studying'], 2, '过去→studied'),
    Q('We ___ (visit) grandma next Sunday.', ['will visit', 'visited', 'visit', 'visiting'], 0, '将来→will visit'),
    Q('I ___ (not see) him last week.', ['don\'t see', 'didn\'t see', 'won\'t see', 'am not seeing'], 1, '过去否定→didn\'t see'),
    Q('___ it rain tomorrow?', ['Does', 'Did', 'Will', 'Is'], 2, '将来疑问→Will'),
    Q('She ___ (be) sick two days ago.', ['is', 'are', 'was', 'were'], 2, '过去→was'),
    Q('They ___ (be) at home last night.', ['is', 'are', 'was', 'were'], 3, '复数过去→were'),
    Q('I ___ going to learn swimming.', ['am', 'was', 'did', 'will'], 0, 'be going to→am going'),
    Q('He ___ (write) a letter tomorrow.', ['writes', 'wrote', 'will write', 'writing'], 2, '将来→will write'),
    Q('They ___ (not come) yesterday.', ['don\'t come', 'didn\'t come', 'won\'t come', 'not come'], 1, '过去否定→didn\'t come'),
  ],
  perfect: [
    Q('I ___ (finish) my homework.', ['have finished', 'has finished', 'finished', 'finishing'], 0, 'I→have+done'),
    Q('She ___ (go) to Beijing.', ['have gone', 'has gone', 'went', 'going'], 1, 'She→has+done'),
    Q('___ you ever ___ to Shanghai?', ['Have, been', 'Has, been', 'Did, been', 'Do, been'], 0, 'Have you been'),
    Q('He has ___ (eat) lunch.', ['eat', 'ate', 'eaten', 'eating'], 2, '过去分词→eaten'),
    Q('They have ___ (see) the movie.', ['see', 'saw', 'seen', 'seeing'], 2, '过去分词→seen'),
    Q('I have ___ (know) him for 3 years.', ['know', 'knew', 'known', 'knowing'], 2, '过去分词→known'),
    Q('She has already ___ (do) it.', ['do', 'did', 'done', 'doing'], 2, '过去分词→done'),
    Q('___ he ___ his homework yet?', ['Have, done', 'Has, done', 'Did, done', 'Does, done'], 1, 'He→Has he done'),
    Q('I have never ___ (be) to Japan.', ['be', 'was', 'been', 'being'], 2, '过去分词→been'),
    Q('She has ___ (write) three books.', ['write', 'wrote', 'written', 'writing'], 2, '过去分词→written'),
    Q('We have lived here ___ 2020.', ['for', 'since', 'in', 'at'], 1, '从某时点→since'),
    Q('He has studied English ___ 5 years.', ['since', 'for', 'in', 'at'], 1, '持续时间段→for'),
    Q('I have just ___ (arrive).', ['arrive', 'arriving', 'arrived', 'arrives'], 2, '过去分词→arrived'),
    Q('They haven\'t ___ (come) yet.', ['come', 'came', 'coming', 'comes'], 0, 'come过去分词→come'),
    Q('Has she ___ (read) the book?', ['read', 'readed', 'reading', 'reads'], 0, 'read过去分词→read'),
  ],
  passive: [
    Q('The window ___ (break) by the boy.', ['was broken', 'is breaking', 'broke', 'breaks'], 0, '被打破→was broken'),
    Q('English ___ (speak) in many countries.', ['speaks', 'is spoken', 'was speaking', 'spoken'], 1, '被说→is spoken'),
    Q('The book ___ (write) by Dickens.', ['wrote', 'was written', 'is writing', 'writes'], 1, '被写→was written'),
    Q('The cake ___ (make) by Mom yesterday.', ['made', 'was made', 'is made', 'makes'], 1, '过去被做→was made'),
    Q('Trees ___ (plant) every spring.', ['plant', 'planted', 'are planted', 'planting'], 2, '被种→are planted'),
    Q('The room ___ (clean) every day.', ['cleans', 'cleaned', 'is cleaned', 'cleaning'], 2, '被打扫→is cleaned'),
    Q('The letter ___ (send) yesterday.', ['sent', 'was sent', 'sends', 'is sent'], 1, '过去被寄→was sent'),
    Q('These cars ___ (make) in Japan.', ['make', 'made', 'are made', 'making'], 2, '被制造→are made'),
    Q('The bridge ___ (build) in 2010.', ['built', 'was built', 'is built', 'builds'], 1, '过去被建→was built'),
    Q('This song ___ (sing) by many people.', ['sings', 'sang', 'is sung', 'singing'], 2, '被唱→is sung'),
    Q('The homework must ___ (finish) today.', ['finished', 'be finished', 'finishes', 'finishing'], 1, '情态+be done'),
    Q('The food ___ (cook) now. (正在被做)', ['is being cooked', 'was cooked', 'cooked', 'cooking'], 0, '正在被做→is being cooked'),
    Q('Milk ___ (drink) by children.', ['drinks', 'is drunk', 'drinking', 'drank'], 1, '被喝→is drunk'),
    Q('The picture ___ (draw) by her.', ['drew', 'was drawn', 'is drawing', 'draws'], 1, '被画→was drawn'),
    Q('The door should ___ (close).', ['closed', 'be closed', 'closes', 'closing'], 1, 'should+be done'),
  ],
  agreement: [
    Q('Everyone ___ here.', ['are', 'is', 'were', 'have'], 1, 'everyone→单数is'),
    Q('The news ___ good.', ['are', 'is', 'were', 'have'], 1, 'news→单数is'),
    Q('Tom and Jerry ___ friends.', ['is', 'are', 'was', 'has'], 1, 'and→复数are'),
    Q('My family ___ having dinner.', ['are', 'is', 'were', 'has'], 1, 'family(整体)→单数'),
    Q('There ___ a book on the desk.', ['are', 'is', 'were', 'have'], 1, '单数→is'),
    Q('There ___ three cats in the room.', ['is', 'are', 'was', 'has'], 1, '复数→are'),
    Q('Math ___ my favorite subject.', ['are', 'is', 'were', 'have'], 1, '学科→单数is'),
    Q('The police ___ looking for him.', ['is', 'are', 'was', 'has'], 1, 'police→复数are'),
    Q('Neither he nor I ___ wrong.', ['is', 'am', 'are', 'was'], 1, '就近原则→I am'),
    Q('Every student ___ a book.', ['have', 'has', 'are having', 'having'], 1, 'every→单数has'),
    Q('Two hours ___ enough.', ['are', 'is', 'were', 'have'], 1, '时间段→单数is'),
    Q('The pair of shoes ___ new.', ['are', 'is', 'were', 'have'], 1, 'a pair of→单数is'),
    Q('Nobody ___ the answer.', ['know', 'knows', 'are knowing', 'knowing'], 1, 'nobody→三单knows'),
    Q('bread and butter ___ my breakfast.', ['are', 'is', 'were', 'have'], 1, '面包黄油(整体)→is'),
    Q('Each of the boys ___ a book.', ['have', 'has', 'are having', 'had'], 1, 'each→三单has'),
  ],
  attrClause: [
    Q('The girl ___ is singing is my sister.', ['which', 'who', 'what', 'where'], 1, '人→who'),
    Q('I like the book ___ you gave me.', ['who', 'which', 'where', 'when'], 1, '物→which'),
    Q('This is the place ___ I was born.', ['which', 'who', 'where', 'that'], 2, '地点→where'),
    Q('I remember the day ___ we met.', ['which', 'who', 'when', 'where'], 2, '时间→when'),
    Q('The man ___ car is red is my uncle.', ['who', 'which', 'whose', 'that'], 2, '谁的→whose'),
    Q('Is this the key ___ you lost?', ['who', 'where', 'that', 'when'], 2, '物→that'),
    Q('She is the teacher ___ taught us English.', ['which', 'who', 'where', 'when'], 1, '人→who'),
    Q('The movie ___ I watched was exciting.', ['who', 'that', 'where', 'when'], 1, '物→that'),
    Q('This is the reason ___ I was late.', ['that', 'which', 'why', 'where'], 2, '原因→why'),
    Q('The house ___ roof is blue is ours.', ['who', 'which', 'whose', 'that'], 2, '谁的→whose'),
    Q('Do you know the boy ___ is standing there?', ['which', 'who', 'where', 'what'], 1, '人→who'),
    Q('The city ___ I live is beautiful.', ['which', 'who', 'that', 'where'], 3, '地点→where'),
    Q('She is the singer ___ voice I love.', ['who', 'that', 'whose', 'which'], 2, '谁的→whose'),
    Q('The school ___ he studies is big.', ['which', 'who', 'that', 'where'], 3, '地点→where'),
    Q('I met a man ___ speaks five languages.', ['which', 'who', 'where', 'when'], 1, '人→who'),
  ],
  subjunctive: [
    Q('If I ___ a bird, I would fly.', ['am', 'were', 'was', 'is'], 1, '虚拟→were'),
    Q('I like apples. — So ___ I.', ['am', 'do', 'can', 'did'], 1, 'like→So do I'),
    Q('She can\'t swim. — Neither ___ I.', ['do', 'am', 'can', 'did'], 2, 'can→Neither can I'),
    Q('___ important to study hard.', ['That is', 'It is', 'This is', 'What is'], 1, '形式主语→It is'),
    Q('If he ___ harder, he would pass.', ['study', 'studies', 'studied', 'studying'], 2, '虚拟过去→studied'),
    Q('There ___ a book and two pens on the desk.', ['is', 'are', 'was', 'has'], 0, '就近→is(a book)'),
    Q('___ easy to learn English.', ['That is', 'It is', 'This is', 'What is'], 1, 'It is+adj+to do'),
    Q('He likes football. — So ___ she.', ['do', 'does', 'is', 'can'], 1, 'likes→So does she'),
    Q('I wish I ___ fly.', ['can', 'could', 'will', 'am'], 1, '虚拟→could'),
    Q('I don\'t like rain. — Neither ___ Tom.', ['do', 'does', 'is', 'can'], 1, 'don\'t→Neither does'),
    Q('___ necessary to be polite.', ['That is', 'It is', 'This is', 'What is'], 1, 'It is necessary'),
    Q('If I ___ you, I would go.', ['am', 'were', 'was', 'is'], 1, '虚拟→were'),
    Q('There ___ some milk in the glass.', ['are', 'is', 'were', 'has'], 1, 'milk不可数→is'),
    Q('___ fun to play games.', ['That is', 'It is', 'This is', 'What is'], 1, 'It is fun to do'),
    Q('She is tired. So ___ we.', ['do', 'does', 'are', 'is'], 2, 'is→So are we'),
  ],
};
