const Q = (stem, options, answer, explanation) => ({ stem, options, answer, explanation });

export const TOPICS_L2 = {
  possessive: {
    key: 'engPossessive', label: '物主代词', icon: '🏷️',
    color: '#338F9B', bg: '#E4F2F3', desc: 'my / your / his / her',
  },
  demonstrative: {
    key: 'engDemo', label: '指示代词', icon: '👉',
    color: '#7BAE8E', bg: '#EDF5F0', desc: 'this / that / these / those',
  },
  uncountable: {
    key: 'engUncount', label: '不可数名词', icon: '💧',
    color: '#5B8A9A', bg: '#E8EEF0', desc: 'water / bread / music',
  },
  timePrep: {
    key: 'engTimePrep', label: '时间介词', icon: '⏰',
    color: '#EB9F4A', bg: '#FDF3E4', desc: 'at / on / in + time',
  },
  comparative: {
    key: 'engCompare', label: '比较级最高级', icon: '📊',
    color: '#9B7EBD', bg: '#F0EBF5', desc: 'bigger / the biggest',
  },
  modal: {
    key: 'engModal', label: '情态动词', icon: '💪',
    color: '#D4839A', bg: '#F8ECF0', desc: 'can / must / should',
  },
  conjunction: {
    key: 'engConj', label: '连词', icon: '🔗',
    color: '#E08B5A', bg: '#FDF0E6', desc: 'and / but / or / because',
  },
  presentSimple: {
    key: 'engPresSimp', label: '一般现在时', icon: '📅',
    color: '#8BA67A', bg: '#EEF3EB', desc: 'I go / She goes',
  },
  presentCont: {
    key: 'engPresCont', label: '现在进行时', icon: '🏃',
    color: '#A0856E', bg: '#F3EDE6', desc: 'am/is/are + doing',
  },
  imperative: {
    key: 'engImperative', label: '祈使句和感叹句', icon: '📢',
    color: '#7E9BAE', bg: '#E8EFF3', desc: 'Open the door! / How nice!',
  },
};

export const LEARN_L2 = {
  possessive: [
    { title: '什么是物主代词？', emoji: '🏷️', body: '物主代词表示"谁的"。\n分为形容词性（放名词前）和名词性（单独用）。', highlight: '物主代词 = "谁的"', examples: [] },
    { title: '形容词性物主代词', emoji: '📋', body: 'my 我的  your 你的\nhis 他的  her 她的  its 它的\nour 我们的  their 他们的', highlight: '放在名词前面：my book', examples: [{ en: 'This is my bag.', zh: '这是我的包。' }, { en: 'Her cat is cute.', zh: '她的猫很可爱。' }] },
    { title: '名词性物主代词', emoji: '🔑', body: 'mine 我的  yours 你的\nhis 他的  hers 她的\nours 我们的  theirs 他们的', highlight: '后面不加名词，独立使用', examples: [{ en: 'This book is mine.', zh: '这本书是我的。' }, { en: 'Is this pen yours?', zh: '这笔是你的吗？' }] },
    { title: '对比记忆', emoji: '💡', body: 'my book = 我的书 (形容词性)\nThis book is mine. = 这书是我的 (名词性)\n\n形容词性 + 名词\n名词性单独用', highlight: '有名词用 my，没名词用 mine', examples: [] },
  ],
  demonstrative: [
    { title: '指示代词', emoji: '👉', body: 'this = 这个（近的单数）\nthat = 那个（远的单数）\nthese = 这些（近的复数）\nthose = 那些（远的复数）', highlight: '近: this/these  远: that/those', examples: [{ en: 'This is a pen.', zh: '这是一支笔。' }, { en: 'Those are my shoes.', zh: '那些是我的鞋。' }] },
    { title: '单数和复数', emoji: '🔢', body: '单数: this / that → is\n复数: these / those → are', highlight: '数量决定用 is 还是 are', examples: [{ en: 'This is an apple.', zh: '这是一个苹果。' }, { en: 'These are apples.', zh: '这些是苹果。' }] },
    { title: '记忆口诀', emoji: '💡', body: '近处单数用 this\n远处单数用 that\n近处复数 these 来\n远处复数 those 在', highlight: '近/远 + 单/复 = 四个指示代词', examples: [] },
  ],
  uncountable: [
    { title: '什么是不可数名词？', emoji: '💧', body: '不可数名词不能一个一个数，\n不能加 a/an，不能加 s。\n如：水、面包、音乐…', highlight: '不能数的东西 = 不可数名词', examples: [] },
    { title: '常见不可数名词', emoji: '📋', body: '液体: water, milk, juice\n食物: bread, rice, meat, cheese\n抽象: music, homework, news\n物质: air, paper, money', highlight: '这些词永远不加 s！', examples: [{ en: 'I want some water.', zh: '我想要一些水。' }, { en: 'She likes music.', zh: '她喜欢音乐。' }] },
    { title: '数量表达', emoji: '🥛', body: '不可数名词用量词来数：\na glass of water 一杯水\na piece of bread 一片面包\na bottle of milk 一瓶牛奶', highlight: '用量词 + of + 不可数名词', examples: [{ en: 'two cups of tea', zh: '两杯茶' }, { en: 'a piece of paper', zh: '一张纸' }] },
    { title: '注意搭配', emoji: '💡', body: '不可数名词前面：\n✓ some, much, a lot of\n✗ a, an, many, 数字', highlight: 'much + 不可数, many + 可数', examples: [{ en: 'How much water do you need?', zh: '你需要多少水？' }] },
  ],
  timePrep: [
    { title: '时间介词 at / on / in', emoji: '⏰', body: '时间介词告诉我们事情发生在什么时候。\n三个最重要的：at, on, in', highlight: '什么时候 → 用时间介词', examples: [] },
    { title: 'at = 在某个时间点', emoji: '🕐', body: 'at + 具体时刻\nat + 特殊时间', highlight: 'at 用于精确时间点', examples: [{ en: 'at 8 o\'clock', zh: '在8点' }, { en: 'at noon', zh: '在中午' }, { en: 'at night', zh: '在晚上' }] },
    { title: 'on = 在某一天', emoji: '📅', body: 'on + 星期几\non + 具体日期', highlight: 'on 用于某一天', examples: [{ en: 'on Monday', zh: '在星期一' }, { en: 'on May 1st', zh: '在5月1日' }, { en: 'on my birthday', zh: '在我的生日' }] },
    { title: 'in = 在某段时间', emoji: '📆', body: 'in + 月份 / 年份\nin + 季节\nin + 上午/下午', highlight: 'in 用于较长时间段', examples: [{ en: 'in June', zh: '在六月' }, { en: 'in 2024', zh: '在2024年' }, { en: 'in the morning', zh: '在早上' }, { en: 'in summer', zh: '在夏天' }] },
    { title: '口诀', emoji: '💡', body: 'at 加时间点（几点钟）\non 加某一天（星期/日期）\nin 加长时间（月/年/季/早午晚）', highlight: '点用at，天用on，长用in', examples: [] },
  ],
  comparative: [
    { title: '比较级', emoji: '📊', body: '比较两个东西时用比较级。\n短词 + er：tall → taller\n长词前加 more：beautiful → more beautiful', highlight: '比较级 = 更...', examples: [{ en: 'Tom is taller than Jerry.', zh: 'Tom 比 Jerry 高。' }] },
    { title: '最高级', emoji: '🏆', body: '三个或以上中最突出的用最高级。\n短词 + est：tall → tallest\n长词前加 most', highlight: '最高级 = 最...', examples: [{ en: 'She is the tallest in class.', zh: '她是班上最高的。' }] },
    { title: '不规则变化', emoji: '⚡', body: 'good/well → better → best\nbad/badly → worse → worst\nmany/much → more → most\nlittle → less → least', highlight: '这四组要死记硬背！', examples: [{ en: 'This book is better than that one.', zh: '这本书比那本好。' }] },
    { title: '比较句型', emoji: '💡', body: 'A is + 比较级 + than B\nA 比 B 更…\n\nA is the + 最高级 + in/of...\nA 是…中最…的', highlight: '比较用 than，最高级用 the', examples: [{ en: 'Summer is hotter than spring.', zh: '夏天比春天热。' }] },
  ],
  modal: [
    { title: '什么是情态动词？', emoji: '💪', body: '情态动词表示能力、许可、义务等。\n后面必须跟动词原形！', highlight: '情态动词 + 动词原形', examples: [] },
    { title: 'can = 能够/可以', emoji: '🦸', body: 'can 表示能力或许可\ncannot = can\'t 表示不能', highlight: 'can 后面动词不变形', examples: [{ en: 'I can swim.', zh: '我会游泳。' }, { en: 'She can\'t fly.', zh: '她不会飞。' }, { en: 'Can you help me?', zh: '你能帮我吗？' }] },
    { title: 'must = 必须', emoji: '⚠️', body: 'must 表示必须做某事\nmust not = mustn\'t 禁止', highlight: 'must = 一定要, mustn\'t = 绝不能', examples: [{ en: 'You must do your homework.', zh: '你必须做作业。' }, { en: 'You mustn\'t be late.', zh: '你不能迟到。' }] },
    { title: 'should = 应该', emoji: '👍', body: 'should 表示建议或应该做的事\nshould not = shouldn\'t', highlight: 'should = 应该（比 must 语气轻）', examples: [{ en: 'You should eat vegetables.', zh: '你应该吃蔬菜。' }, { en: 'You shouldn\'t stay up late.', zh: '你不应该熬夜。' }] },
  ],
  conjunction: [
    { title: '什么是连词？', emoji: '🔗', body: '连词用来连接词、短语或句子。\n就像桥梁一样！', highlight: '连词 = 连接的桥梁', examples: [] },
    { title: 'and = 和/而且', emoji: '➕', body: 'and 连接两个并列的东西', highlight: '加法逻辑：A and B', examples: [{ en: 'I like cats and dogs.', zh: '我喜欢猫和狗。' }, { en: 'She is tall and thin.', zh: '她又高又瘦。' }] },
    { title: 'but = 但是', emoji: '↩️', body: 'but 表示转折', highlight: '转折逻辑：A but B', examples: [{ en: 'He is short but strong.', zh: '他矮但是强壮。' }, { en: 'I like math but not English.', zh: '我喜欢数学但不喜欢英语。' }] },
    { title: 'or = 或者 / because = 因为', emoji: '🔀', body: 'or 表示选择\nbecause 表示原因', highlight: 'or = 选择, because = 原因', examples: [{ en: 'Tea or coffee?', zh: '茶还是咖啡？' }, { en: 'I\'m happy because it\'s sunny.', zh: '我开心因为天晴了。' }] },
  ],
  presentSimple: [
    { title: '什么是一般现在时？', emoji: '📅', body: '一般现在时表示：\n经常做的事、习惯、事实。', highlight: '经常/总是/每天做的事', examples: [] },
    { title: '主语是 I/you/we/they', emoji: '👥', body: '动词用原形，不变！', highlight: '我/你/我们/他们 + 动词原形', examples: [{ en: 'I go to school every day.', zh: '我每天上学。' }, { en: 'They play football.', zh: '他们踢足球。' }] },
    { title: '三单变化 (he/she/it)', emoji: '👆', body: '动词要加 s 或 es：\n一般加 s: runs, likes\n以 s/x/sh/ch/o 结尾加 es: goes, watches\n辅音+y → ies: studies', highlight: '第三人称单数动词要变！', examples: [{ en: 'He goes to school.', zh: '他去上学。' }, { en: 'She watches TV.', zh: '她看电视。' }] },
    { title: '否定和疑问', emoji: '❓', body: '否定: don\'t/doesn\'t + 动词原形\n疑问: Do/Does + 主语 + 动词原形?', highlight: '用了 does/doesn\'t 动词要还原！', examples: [{ en: 'She doesn\'t like fish.', zh: '她不喜欢鱼。' }, { en: 'Does he play tennis?', zh: '他打网球吗？' }] },
  ],
  presentCont: [
    { title: '什么是现在进行时？', emoji: '🏃', body: '现在进行时表示正在做的事。\n格式: am/is/are + doing', highlight: '正在...', examples: [] },
    { title: '怎么加 -ing', emoji: '✏️', body: '一般直接加: read → reading\n去e加ing: write → writing\n双写末尾: run → running, swim → swimming', highlight: '注意双写和去e！', examples: [{ en: 'I am reading a book.', zh: '我正在看书。' }, { en: 'She is writing.', zh: '她正在写字。' }] },
    { title: '否定和疑问', emoji: '❓', body: '否定: am/is/are + not + doing\n疑问: Am/Is/Are + 主语 + doing?', highlight: 'be动词提前变疑问', examples: [{ en: 'He is not sleeping.', zh: '他没在睡觉。' }, { en: 'Are you watching TV?', zh: '你在看电视吗？' }] },
    { title: '常用时间词', emoji: '💡', body: 'now 现在  right now 就现在\nlook! 看！  listen! 听！\nat the moment 此刻', highlight: '看到这些词考虑进行时！', examples: [{ en: 'Look! The cat is sleeping.', zh: '看！猫正在睡觉。' }] },
  ],
  imperative: [
    { title: '祈使句', emoji: '📢', body: '祈使句用来命令、请求或建议。\n直接用动词原形开头，省略主语 you。', highlight: '动词原形开头 = 祈使句', examples: [{ en: 'Open the door.', zh: '开门。' }, { en: 'Please sit down.', zh: '请坐下。' }] },
    { title: '否定祈使句', emoji: '🚫', body: 'Don\'t + 动词原形 = 不要…', highlight: 'Don\'t 开头 = 不要做某事', examples: [{ en: 'Don\'t run in the hall.', zh: '不要在走廊跑。' }, { en: 'Don\'t be late.', zh: '不要迟到。' }] },
    { title: '感叹句 What', emoji: '😲', body: 'What + a/an + 形容词 + 名词!\nWhat 用来感叹名词。', highlight: 'What + 名词(短语)!', examples: [{ en: 'What a nice day!', zh: '多好的一天！' }, { en: 'What beautiful flowers!', zh: '多漂亮的花！' }] },
    { title: '感叹句 How', emoji: '😍', body: 'How + 形容词/副词!\nHow 用来感叹形容词或副词。', highlight: 'How + 形容词!', examples: [{ en: 'How beautiful!', zh: '多漂亮啊！' }, { en: 'How fast he runs!', zh: '他跑得多快！' }] },
  ],
};

export const QUESTIONS_L2 = {
  possessive: [
    Q('This is ___ book. (我的)', ['I', 'me', 'my', 'mine'], 2, '我的+名词 → my'),
    Q('Is this pen ___? (你的)', ['you', 'your', 'yours', 'yourself'], 2, '名词性→yours(独立)'),
    Q('___ name is Tom. (他的)', ['He', 'Him', 'His', 'Her'], 2, '他的+名词 → His'),
    Q('The cat lost ___ tail. (它的)', ['it', 'it\'s', 'its', 'their'], 2, '它的 → its'),
    Q('This bag is ___. (她的)', ['she', 'her', 'hers', 'herself'], 2, '名词性→hers'),
    Q('We love ___ school. (我们的)', ['us', 'we', 'ours', 'our'], 3, '我们的+名词→our'),
    Q('___ house is very big. (他们的)', ['They', 'Them', 'Theirs', 'Their'], 3, '他们的+名词→Their'),
    Q('Is this book ___? (我的)', ['my', 'me', 'I', 'mine'], 3, '名词性→mine(独立)'),
    Q('She washes ___ hands. (她的)', ['she', 'hers', 'her', 'herself'], 2, '她的+名词→her'),
    Q('The dog wagged ___ tail. (它的)', ['it', 'its', 'it\'s', 'itself'], 1, '它的→its(无撇号)'),
    Q('This car is ___. (我们的)', ['our', 'us', 'ours', 'we'], 2, '名词性→ours'),
    Q('___ father is a doctor. (我的)', ['I', 'Me', 'My', 'Mine'], 2, '我的+名词→My'),
    Q('Are these toys ___? (他们的)', ['they', 'their', 'theirs', 'them'], 2, '名词性→theirs'),
    Q('Give me ___ pen. (你的)', ['you', 'your', 'yours', 'yourself'], 1, '你的+名词→your'),
    Q('___ brother is tall. (她的)', ['She', 'Hers', 'Her', 'Herself'], 2, '她的+名词→Her'),
  ],
  demonstrative: [
    Q('___ is my pen. (这个，近)', ['That', 'These', 'This', 'Those'], 2, '近+单数→This'),
    Q('___ are my books. (这些，近)', ['This', 'That', 'These', 'Those'], 2, '近+复数→These'),
    Q('___ is a dog. (那个，远)', ['This', 'That', 'These', 'Those'], 1, '远+单数→That'),
    Q('___ are my friends. (那些，远)', ['This', 'That', 'These', 'Those'], 3, '远+复数→Those'),
    Q('___ flowers are beautiful. (这些)', ['This', 'That', 'These', 'Those'], 2, '近+复数→These'),
    Q('What is ___? — It\'s a bird. (那个)', ['this', 'that', 'these', 'those'], 1, '远+单数→that'),
    Q('___ is an apple on the table.', ['This', 'These', 'That', 'Those'], 0, '单数→This/That + is'),
    Q('Are ___ your shoes? (这些)', ['this', 'that', 'these', 'those'], 2, '复数→these'),
    Q('___ boy is my brother. (那个)', ['This', 'That', 'These', 'Those'], 1, '远+单数→That'),
    Q('I like ___ pictures. (这些)', ['this', 'that', 'these', 'those'], 2, '近+复数→these'),
    Q('___ cakes are delicious! (那些)', ['This', 'That', 'These', 'Those'], 3, '远+复数→Those'),
    Q('Look at ___ car! (那辆)', ['this', 'that', 'these', 'those'], 1, '远+单数→that'),
    Q('___ is my seat. (这个)', ['These', 'Those', 'This', 'That'], 2, '近+单数→This'),
    Q('Who are ___ people? (那些)', ['this', 'that', 'these', 'those'], 3, '远+复数→those'),
    Q('___ ___ your keys? (这些是)', ['This is', 'That is', 'These are', 'Those is'], 2, '复数→These are'),
  ],
  uncountable: [
    Q('I need some ___. (水)', ['waters', 'a water', 'water', 'the waters'], 2, 'water 不可数'),
    Q('How ___ milk do you want?', ['many', 'much', 'few', 'little'], 1, '不可数→much'),
    Q('She has ___ rice.', ['a', 'an', 'some', 'many'], 2, 'rice 不可数→some'),
    Q('There is ___ bread on the table.', ['a', 'many', 'some', 'few'], 2, 'bread 不可数→some'),
    Q('How ___ apples do you have?', ['much', 'many', 'few', 'little'], 1, '可数→many'),
    Q('I want a glass of ___.', ['waters', 'water', 'the water', 'a water'], 1, 'a glass of + 不可数'),
    Q('___ is important for us. (音乐)', ['Musics', 'A music', 'Music', 'The musics'], 2, 'music 不可数'),
    Q('Can I have ___ paper?', ['a', 'an', 'some', 'many'], 2, 'paper 不可数→some'),
    Q('There isn\'t ___ money.', ['many', 'much', 'few', 'a'], 1, 'money 不可数→much'),
    Q('I need two ___ of bread.', ['piece', 'pieces', 'breads', 'slice'], 1, 'two pieces of'),
    Q('___ is bad for your teeth. (糖)', ['Sugars', 'A sugar', 'Sugar', 'The sugars'], 2, 'sugar 不可数'),
    Q('How ___ homework do you have?', ['many', 'much', 'few', 'several'], 1, 'homework 不可数→much'),
    Q('She drinks ___ juice every day.', ['a', 'an', 'some', 'many'], 2, 'juice 不可数→some'),
    Q('I ate three ___ of cake.', ['cakes', 'piece', 'pieces', 'cake'], 2, 'three pieces of'),
    Q('We need ___ more time.', ['a', 'many', 'some', 'few'], 2, 'time 不可数→some'),
  ],
  timePrep: [
    Q('I wake up ___ 7 o\'clock.', ['in', 'on', 'at', 'to'], 2, '具体时刻→at'),
    Q('We have PE ___ Monday.', ['in', 'on', 'at', 'to'], 1, '星期几→on'),
    Q('My birthday is ___ May.', ['in', 'on', 'at', 'to'], 0, '月份→in'),
    Q('She goes to bed ___ night.', ['in', 'on', 'at', 'to'], 2, 'at night'),
    Q('It\'s cold ___ winter.', ['in', 'on', 'at', 'to'], 0, '季节→in'),
    Q('We eat lunch ___ noon.', ['in', 'on', 'at', 'to'], 2, 'at noon'),
    Q('I read books ___ the morning.', ['at', 'on', 'in', 'to'], 2, 'in the morning'),
    Q('The party is ___ Saturday.', ['in', 'on', 'at', 'to'], 1, '星期几→on'),
    Q('He was born ___ 2016.', ['in', 'on', 'at', 'to'], 0, '年份→in'),
    Q('School starts ___ 8:30.', ['in', 'on', 'at', 'to'], 2, '时刻→at'),
    Q('We have a test ___ Friday.', ['in', 'at', 'on', 'to'], 2, '星期几→on'),
    Q('Birds sing ___ the morning.', ['at', 'on', 'in', 'to'], 2, 'in the morning'),
    Q('She arrives ___ 3 o\'clock.', ['in', 'on', 'at', 'to'], 2, '时刻→at'),
    Q('We go swimming ___ summer.', ['at', 'on', 'in', 'to'], 2, '季节→in'),
    Q('The meeting is ___ January 5th.', ['in', 'on', 'at', 'to'], 1, '具体日期→on'),
  ],
  comparative: [
    Q('Tom is ___ than Jerry. (tall)', ['taller', 'tallest', 'more tall', 'most tall'], 0, '短词+er→taller'),
    Q('She is the ___ in class. (tall)', ['taller', 'tallest', 'more tall', 'most tall'], 1, '最高级+est→tallest'),
    Q('This book is ___ than that one. (good)', ['gooder', 'more good', 'better', 'best'], 2, 'good→better'),
    Q('He is the ___ student. (good)', ['better', 'gooder', 'most good', 'best'], 3, 'good→best'),
    Q('Summer is ___ than spring. (hot)', ['hoter', 'hotter', 'more hot', 'hottest'], 1, '双写+er→hotter'),
    Q('This is the ___ day of the year. (cold)', ['colder', 'more cold', 'coldest', 'most cold'], 2, '短词+est→coldest'),
    Q('She is ___ than me. (beautiful)', ['beautifuler', 'more beautiful', 'most beautiful', 'beautifuller'], 1, '长词→more beautiful'),
    Q('It is the ___ flower. (beautiful)', ['beautifulest', 'more beautiful', 'most beautiful', 'beautifuller'], 2, '长词→most beautiful'),
    Q('My bag is ___ than yours. (big)', ['biger', 'bigger', 'more big', 'biggest'], 1, '双写+er→bigger'),
    Q('This is ___ than that. (bad)', ['badder', 'more bad', 'worse', 'worst'], 2, 'bad→worse'),
    Q('He runs ___ than me. (fast)', ['faster', 'fastest', 'more fast', 'more faster'], 0, '短词+er→faster'),
    Q('She is the ___ girl in school. (pretty)', ['prettier', 'prettiest', 'most pretty', 'more pretty'], 1, 'y→iest'),
    Q('An elephant is ___ than a cat. (heavy)', ['heavier', 'more heavy', 'heaviest', 'heavy'], 0, 'y→ier'),
    Q('This is the ___ movie ever. (bad)', ['worse', 'baddest', 'more bad', 'worst'], 3, 'bad→worst'),
    Q('My sister is ___ than me. (young)', ['younger', 'youngest', 'more young', 'most young'], 0, '短词+er→younger'),
  ],
  modal: [
    Q('I ___ swim. (能)', ['can', 'must', 'should', 'am'], 0, '能→can'),
    Q('You ___ do your homework. (必须)', ['can', 'must', 'may', 'might'], 1, '必须→must'),
    Q('You ___ eat more vegetables. (应该)', ['can', 'must', 'should', 'would'], 2, '应该→should'),
    Q('___ I go to the bathroom?', ['Should', 'Must', 'Can', 'Would'], 2, '我可以去吗→Can I'),
    Q('She ___ speak English well.', ['can', 'cans', 'is can', 'caning'], 0, '情态动词不变形'),
    Q('You ___ run in the library.', ['can', 'must', 'mustn\'t', 'should'], 2, '不许→mustn\'t'),
    Q('He ___ play the piano. (会)', ['can', 'must', 'should', 'has'], 0, '会→can'),
    Q('We ___ help others. (应该)', ['can', 'must', 'should', 'might'], 2, '应该→should'),
    Q('You ___ be late for school.', ['can', 'should', 'mustn\'t', 'couldn\'t'], 2, '不可以→mustn\'t'),
    Q('___ you pass me the salt?', ['Must', 'Should', 'Can', 'Are'], 2, '能否→Can you'),
    Q('She ___ dance very well. (能)', ['cans', 'can', 'is can', 'must'], 1, 'can 不加s'),
    Q('We ___ listen in class. (应该)', ['can', 'must', 'should', 'might'], 2, '应该→should'),
    Q('He ___ finish it today. (必须)', ['can', 'should', 'must', 'might'], 2, '必须→must'),
    Q('You ___ touch that! It\'s hot!', ['can', 'should', 'mustn\'t', 'don\'t'], 2, '不许→mustn\'t'),
    Q('I ___ ride a bike now. (能)', ['must', 'should', 'can', 'may'], 2, '能→can'),
  ],
  conjunction: [
    Q('I like tea ___ coffee.', ['but', 'or', 'and', 'because'], 2, '和→and'),
    Q('She is small ___ strong.', ['and', 'but', 'or', 'because'], 1, '但是→but'),
    Q('Do you want milk ___ juice?', ['and', 'but', 'or', 'because'], 2, '或者→or'),
    Q('I stayed home ___ it was raining.', ['and', 'but', 'or', 'because'], 3, '因为→because'),
    Q('He is smart ___ funny.', ['but', 'or', 'and', 'because'], 2, '又...又→and'),
    Q('I want to go ___ I\'m too tired.', ['and', 'but', 'or', 'because'], 1, '但是→but'),
    Q('Is it a cat ___ a dog?', ['and', 'but', 'or', 'because'], 2, '还是→or'),
    Q('She cried ___ she was sad.', ['and', 'but', 'or', 'because'], 3, '因为→because'),
    Q('We can walk ___ take the bus.', ['but', 'because', 'or', 'so'], 2, '或者→or'),
    Q('He is rich ___ not happy.', ['and', 'but', 'or', 'because'], 1, '但是→but'),
    Q('I study hard ___ I want to pass.', ['but', 'or', 'and', 'because'], 3, '因为→because'),
    Q('She likes music ___ dancing.', ['but', 'or', 'and', 'because'], 2, '和→and'),
    Q('Hurry up, ___ you\'ll be late.', ['and', 'but', 'or', 'because'], 2, '否则→or'),
    Q('I\'m hungry ___ thirsty.', ['but', 'or', 'and', 'because'], 2, '和→and'),
    Q('He didn\'t come ___ he was ill.', ['and', 'but', 'or', 'because'], 3, '因为→because'),
  ],
  presentSimple: [
    Q('She ___ (go) to school every day.', ['go', 'goes', 'going', 'gone'], 1, '三单+es→goes'),
    Q('They ___ (play) basketball.', ['plays', 'play', 'playing', 'played'], 1, 'They+原形→play'),
    Q('He ___ (watch) TV at night.', ['watch', 'watches', 'watching', 'watched'], 1, '三单+es→watches'),
    Q('I ___ (like) ice cream.', ['likes', 'like', 'liking', 'liked'], 1, 'I+原形→like'),
    Q('My mother ___ (cook) dinner.', ['cook', 'cooks', 'cooking', 'cooked'], 1, '三单+s→cooks'),
    Q('She ___ (study) English hard.', ['study', 'studies', 'studying', 'studied'], 1, '三单y→ies'),
    Q('We ___ (have) lunch at noon.', ['has', 'have', 'having', 'had'], 1, 'We+原形→have'),
    Q('He ___ (not like) fish.', ['don\'t like', 'doesn\'t like', 'not like', 'isn\'t like'], 1, '三单否定→doesn\'t'),
    Q('___ she ___ English? (speak)', ['Do, speak', 'Does, speak', 'Does, speaks', 'Is, speak'], 1, '三单疑问→Does+原形'),
    Q('The sun ___ (rise) in the east.', ['rise', 'rises', 'rising', 'rose'], 1, '客观事实三单→rises'),
    Q('I ___ (not eat) meat.', ['doesn\'t eat', 'don\'t eat', 'am not eat', 'not eat'], 1, 'I否定→don\'t'),
    Q('___ you like music? (一般疑问)', ['Does', 'Do', 'Are', 'Is'], 1, 'you→Do'),
    Q('My father ___ (drive) to work.', ['drive', 'drives', 'driving', 'drove'], 1, '三单+s→drives'),
    Q('The bus ___ (come) at 8.', ['come', 'comes', 'coming', 'came'], 1, '三单+s→comes'),
    Q('She ___ (have) a cat.', ['have', 'has', 'having', 'had'], 1, '三单→has'),
  ],
  presentCont: [
    Q('I ___ (read) a book now.', ['read', 'am reading', 'reads', 'reading'], 1, 'I+am+doing'),
    Q('She ___ (write) a letter.', ['writes', 'is writing', 'writing', 'write'], 1, 'She+is+doing'),
    Q('They ___ (play) in the park.', ['play', 'are playing', 'plays', 'playing'], 1, 'They+are+doing'),
    Q('Look! The bird ___ (fly).', ['flies', 'is flying', 'fly', 'flying'], 1, 'Look!→进行时'),
    Q('He ___ (not sleep) now.', ['doesn\'t sleep', 'isn\'t sleeping', 'not sleeping', 'don\'t sleep'], 1, 'is not doing'),
    Q('___ you ___ TV? (watch)', ['Do, watch', 'Are, watching', 'Does, watch', 'Is, watching'], 1, 'Are you doing?'),
    Q('We ___ (have) dinner now.', ['have', 'are having', 'has', 'having'], 1, 'We+are+doing'),
    Q('She ___ (run) in the garden.', ['runs', 'is running', 'run', 'running'], 1, '双写n→running'),
    Q('I ___ (swim) in the pool.', ['swim', 'am swimming', 'swims', 'swimming'], 1, '双写m→swimming'),
    Q('The children ___ (sing) happily.', ['sing', 'are singing', 'sings', 'singing'], 1, 'They→are singing'),
    Q('He ___ (sit) on the chair.', ['sits', 'is sitting', 'sit', 'sitting'], 1, '双写t→sitting'),
    Q('Mom ___ (cook) in the kitchen.', ['cooks', 'is cooking', 'cook', 'cooking'], 1, 'Mom→is cooking'),
    Q('___ it ___ now? (rain)', ['Does, rain', 'Is, raining', 'Do, rain', 'Are, raining'], 1, 'Is it raining?'),
    Q('They ___ (not study) right now.', ['don\'t study', 'aren\'t studying', 'isn\'t studying', 'not studying'], 1, 'aren\'t+doing'),
    Q('Listen! She ___ (sing) a song.', ['sings', 'is singing', 'sing', 'singing'], 1, 'Listen!→进行时'),
  ],
  imperative: [
    Q('___ the door, please.', ['Opens', 'Open', 'Opening', 'Opened'], 1, '祈使句→动词原形'),
    Q('___ run in the hall!', ['Not', 'Doesn\'t', 'Don\'t', 'Isn\'t'], 2, '否定祈使→Don\'t'),
    Q('___ quiet, please.', ['Are', 'Is', 'Be', 'Being'], 2, '祈使句→Be quiet'),
    Q('___ a nice day!', ['What', 'How', 'Where', 'When'], 0, 'What a nice day!'),
    Q('___ beautiful the flowers are!', ['What', 'How', 'Where', 'When'], 1, 'How+形容词!'),
    Q('Please ___ down.', ['sitting', 'sits', 'sit', 'sat'], 2, '祈使句→动词原形'),
    Q('___ touch that! It\'s hot!', ['Not', 'Don\'t', 'Isn\'t', 'Doesn\'t'], 1, 'Don\'t+动词原形'),
    Q('___ a clever boy he is!', ['What', 'How', 'Where', 'Why'], 0, 'What+a+n!'),
    Q('___ fast he runs!', ['What', 'How', 'Where', 'Why'], 1, 'How+adj/adv!'),
    Q('___ careful on the road.', ['Are', 'Is', 'Be', 'Being'], 2, 'Be careful!'),
    Q('Let\'s ___ to the park.', ['going', 'goes', 'go', 'went'], 2, 'Let\'s+动词原形'),
    Q('___ a big cake!', ['How', 'What', 'Where', 'Who'], 1, 'What+a+n!'),
    Q('___ delicious the food is!', ['What', 'How', 'Where', 'Who'], 1, 'How+adj!'),
    Q('Please ___ late.', ['not be', 'don\'t be', 'isn\'t', 'no be'], 1, 'don\'t be late'),
    Q('___ turn left at the corner.', ['Please', 'Pleasing', 'Pleased', 'Pleasure'], 0, 'Please+祈使句'),
  ],
};
