const Q = (stem, options, answer, explanation) => ({ stem, options, answer, explanation });

export const TOPICS_L1 = {
  pronoun: {
    key: 'engPronoun', label: '人称代词', icon: '👤',
    color: '#338F9B', bg: '#E4F2F3', desc: 'I / you / he / she / it',
  },
  article: {
    key: 'engArticle', label: '冠词 a / an', icon: '📖',
    color: '#7BAE8E', bg: '#EDF5F0', desc: 'a cat / an apple',
  },
  plural: {
    key: 'engPlural', label: '名词单复数', icon: '🔤',
    color: '#EB9F4A', bg: '#FDF3E4', desc: 'cat → cats',
  },
  prep: {
    key: 'engPrep', label: '方位介词', icon: '📍',
    color: '#9B7EBD', bg: '#F0EBF5', desc: 'in / on / under',
  },
  beVerb: {
    key: 'engBeVerb', label: 'am / is / are', icon: '✏️',
    color: '#D4839A', bg: '#F8ECF0', desc: 'I am, She is',
  },
  adjective: {
    key: 'engAdj', label: '形容词', icon: '🌈',
    color: '#E08B5A', bg: '#FDF0E6', desc: 'big ↔ small',
  },
  numbers: {
    key: 'engNumbers', label: '数词', icon: '🔢',
    color: '#5B8A9A', bg: '#E8EEF0', desc: 'one / first',
  },
  sentence: {
    key: 'engSentence', label: '基本句型', icon: '💬',
    color: '#8BA67A', bg: '#EEF3EB', desc: 'This is... / There is...',
  },
  declarative: {
    key: 'engDeclarative', label: '陈述句', icon: '📄',
    color: '#A0856E', bg: '#F3EDE6', desc: '肯定句 / 否定句',
  },
  question: {
    key: 'engQuestion', label: '简单疑问句', icon: '❓',
    color: '#7E9BAE', bg: '#E8EFF3', desc: 'What / Where / Who',
  },
};

export const LEARN_L1 = {
  pronoun: [
    { title: '什么是人称代词？', emoji: '👋', body: '人称代词就是用来代替人名的小词语。\n比如不说"小明"，可以说 "he"（他）。', highlight: '代词让句子更简短！', examples: [] },
    { title: 'I 和 you', emoji: '🙋', body: 'I = 我 （永远大写哦！）\nyou = 你 / 你们', highlight: 'I 不管在哪里都要大写！', examples: [{ en: 'I am a boy.', zh: '我是一个男孩。' }, { en: 'You are my friend.', zh: '你是我的朋友。' }] },
    { title: 'he / she / it', emoji: '👦👧🐱', body: 'he = 他（男孩、爸爸）\nshe = 她（女孩、妈妈）\nit = 它（动物、东西）', highlight: '男用 he，女用 she，其他用 it', examples: [{ en: 'He is tall.', zh: '他很高。' }, { en: 'She is kind.', zh: '她很善良。' }, { en: 'It is a cat.', zh: '它是一只猫。' }] },
    { title: 'we 和 they', emoji: '👨‍👩‍👧‍👦', body: 'we = 我们（包括我自己）\nthey = 他们（不包括我）', highlight: '有我 → we，没我 → they', examples: [{ en: 'We are happy.', zh: '我们很开心。' }, { en: 'They are students.', zh: '他们是学生。' }] },
    { title: '记忆口诀', emoji: '💡', body: '我 I 你 you 他 he\n她 she 它 it 记心间\n我们 we 他们 they\n七个代词手拉手！', highlight: '试着背一背这个口诀！', examples: [] },
  ],
  article: [
    { title: '什么是冠词？', emoji: '📖', body: 'a 和 an 是"冠词"，放在名词前面。\n就像给名词戴一顶帽子！', highlight: '"一个"苹果 → an apple', examples: [] },
    { title: '什么时候用 a？', emoji: '🐶', body: '当后面的单词读起来是辅音开头时，用 a。\n大部分字母开头的词都用 a！', highlight: 'a + 辅音开头', examples: [{ en: 'a cat', zh: '一只猫' }, { en: 'a dog', zh: '一只狗' }, { en: 'a book', zh: '一本书' }] },
    { title: '什么时候用 an？', emoji: '🍎', body: '当后面的单词读起来是元音开头时，用 an。', highlight: '元音字母口诀：a e i o u', examples: [{ en: 'an apple', zh: '一个苹果' }, { en: 'an egg', zh: '一个鸡蛋' }, { en: 'an orange', zh: '一个橙子' }, { en: 'an umbrella', zh: '一把雨伞' }] },
    { title: '超级口诀', emoji: '💡', body: 'a e i o u 五兄弟\n看到它们用 an\n其他字母用 a\n记住口诀不出错！', highlight: 'a e i o u → an，其他 → a', examples: [] },
  ],
  plural: [
    { title: '什么是单数和复数？', emoji: '🐱🐱', body: '一个东西 = 单数\n两个或更多 = 复数\n复数通常在后面加 s 或 es', highlight: '1个用单数，2个以上用复数！', examples: [] },
    { title: '加 s 变复数', emoji: '✨', body: '大多数名词，直接加 s 就行！', highlight: '最简单的规则！', examples: [{ en: 'cat → cats', zh: '猫 → 猫们' }, { en: 'dog → dogs', zh: '狗 → 狗们' }, { en: 'book → books', zh: '书 → 书们' }] },
    { title: '加 es 变复数', emoji: '📦', body: '以 s, x, sh, ch 结尾的词，加 es！', highlight: '结尾是 s/x/sh/ch → 加 es', examples: [{ en: 'box → boxes', zh: '盒子 → 盒子们' }, { en: 'bus → buses', zh: '公交车 → 公交车们' }] },
    { title: '特殊变化', emoji: '🦸', body: '有些名词复数不加 s，要特别记住：', highlight: '特殊词要记牢！', examples: [{ en: 'man → men', zh: '男人' }, { en: 'woman → women', zh: '女人' }, { en: 'child → children', zh: '孩子' }, { en: 'foot → feet', zh: '脚' }] },
  ],
  prep: [
    { title: '什么是方位介词？', emoji: '🗺️', body: '方位介词告诉我们东西在哪里。', highlight: '用介词说出物品的位置！', examples: [] },
    { title: 'in = 在…里面', emoji: '📦', body: '想象一个盒子，东西在里面：', highlight: 'in → 里面', examples: [{ en: 'The ball is in the box.', zh: '球在盒子里面。' }], visual: { type: 'position', lines: ['  ┌────────┐', '  │ ⚽ 📦 │', '  └────────┘', '  球在盒子里 → in'] } },
    { title: 'on = 在…上面', emoji: '📚', body: '东西放在表面上、接触着：', highlight: 'on → 上面（接触）', examples: [{ en: 'The book is on the desk.', zh: '书在桌子上面。' }], visual: { type: 'position', lines: ['    ⚽', '  ────────', '  球在桌子上 → on'] } },
    { title: 'under = 在…下面', emoji: '👇', body: '东西在另一个东西的下面：', highlight: 'under → 下面', examples: [{ en: 'The cat is under the table.', zh: '猫在桌子下面。' }], visual: { type: 'position', lines: ['  ────────', '    ⚽', '  球在桌子下 → under'] } },
    { title: '记忆画面', emoji: '💡', body: 'in  → 🐱📦 猫钻进盒子里\non  → 🐱📦 猫坐在盒子上\nunder → 📦🐱 猫躲在盒子下\nbehind → 📦 🐱 猫藏在盒子后', highlight: '想象小猫在盒子的不同位置！', examples: [] },
  ],
  beVerb: [
    { title: '什么是 be 动词？', emoji: '✏️', body: 'be 动词就是 am、is、are。\n它们的意思都是"是"。', highlight: 'am / is / are 都是"是"', examples: [] },
    { title: 'I → am', emoji: '🙋', body: '"我"永远用 am！\nI am = I\'m（缩写）', highlight: 'I + am，独一无二的搭配！', examples: [{ en: 'I am a student.', zh: '我是学生。' }, { en: 'I am happy.', zh: '我很开心。' }] },
    { title: 'he / she / it → is', emoji: '👆', body: '一个人或一个东西，用 is', highlight: '单个的他/她/它 → is', examples: [{ en: 'He is a boy.', zh: '他是一个男孩。' }, { en: 'She is my mom.', zh: '她是我妈妈。' }] },
    { title: 'you / we / they → are', emoji: '👥', body: '"你""我们""他们"用 are', highlight: '你/我们/他们 → are', examples: [{ en: 'You are kind.', zh: '你很善良。' }, { en: 'We are friends.', zh: '我们是朋友。' }] },
    { title: '口诀', emoji: '💡', body: 'I 用 am\nyou 用 are\nis 跟着 he / she / it\nwe / they 都用 are', highlight: '背熟口诀，做题飞快！', examples: [] },
  ],
  adjective: [
    { title: '什么是形容词？', emoji: '🌈', body: '形容词是描述东西的词。\n比如：大的、小的、高的…', highlight: '形容词 = 描述词', examples: [] },
    { title: '大小和高矮', emoji: '🐘🐭', body: 'big = 大 ↔ small = 小\ntall = 高 ↔ short = 矮\nlong = 长 ↔ short = 短', highlight: '反义词要一起记！', examples: [{ en: 'The elephant is big.', zh: '大象是大的。' }, { en: 'The mouse is small.', zh: '老鼠是小的。' }] },
    { title: '感受和心情', emoji: '😊😢', body: 'happy = 开心 ↔ sad = 伤心\nhot = 热 ↔ cold = 冷\nnew = 新 ↔ old = 旧', highlight: '形容词告诉我们感觉如何！', examples: [{ en: 'I am happy.', zh: '我很开心。' }, { en: 'It is cold today.', zh: '今天很冷。' }] },
    { title: '颜色也是形容词', emoji: '🎨', body: 'red 红  blue 蓝  green 绿\nyellow 黄  white 白  black 黑', highlight: '颜色放在名词前面！', examples: [{ en: 'a red apple', zh: '一个红苹果' }, { en: 'a blue sky', zh: '蓝色的天空' }] },
  ],
  numbers: [
    { title: '基数词 1-10', emoji: '🔢', body: '1 one  2 two  3 three  4 four  5 five\n6 six  7 seven  8 eight  9 nine  10 ten', highlight: '基数词表示数量多少', examples: [{ en: 'I have two cats.', zh: '我有两只猫。' }, { en: 'There are five apples.', zh: '有五个苹果。' }] },
    { title: '基数词 11-20', emoji: '🔢', body: '11 eleven  12 twelve  13 thirteen\n14 fourteen  15 fifteen  16 sixteen\n17 seventeen  18 eighteen  19 nineteen  20 twenty', highlight: '13-19 都以 -teen 结尾', examples: [{ en: 'She is twelve years old.', zh: '她12岁了。' }] },
    { title: '序数词', emoji: '🏆', body: '1st first  2nd second  3rd third\n4th fourth  5th fifth  6th sixth\n7th seventh  8th eighth  9th ninth  10th tenth', highlight: '序数词表示顺序（第几）', examples: [{ en: 'I am the first.', zh: '我是第一名。' }, { en: 'She is in the third grade.', zh: '她在三年级。' }] },
    { title: '记忆口诀', emoji: '💡', body: '基变序有规律\n一二三特殊记 (first, second, third)\n其余加 th 就可以\nfive 要把 ve 变 f (fifth)\neight 去 t (eighth)\nnine 去 e (ninth)', highlight: '1st/2nd/3rd 要特殊记忆！', examples: [] },
  ],
  sentence: [
    { title: '主语 + 谓语 + 宾语', emoji: '💬', body: '英语最基本的句子格式：\n谁 + 做什么 + 什么东西\nI like apples. = 我 喜欢 苹果', highlight: '主 + 谓 + 宾 是最常见的句型', examples: [{ en: 'I like apples.', zh: '我喜欢苹果。' }, { en: 'She reads books.', zh: '她看书。' }] },
    { title: 'This is... / That is...', emoji: '👉', body: 'This is = 这是（近的）\nThat is = 那是（远的）', highlight: '近用 this，远用 that', examples: [{ en: 'This is my pen.', zh: '这是我的笔。' }, { en: 'That is a bird.', zh: '那是一只鸟。' }] },
    { title: 'I have...', emoji: '🎒', body: 'I have = 我有\nShe has = 她有（注意第三人称用 has）', highlight: '我/你/我们/他们 → have; 他/她/它 → has', examples: [{ en: 'I have a dog.', zh: '我有一只狗。' }, { en: 'She has a red dress.', zh: '她有一条红裙子。' }] },
    { title: 'There is / There are', emoji: '🏠', body: 'There is = 有（一个）\nThere are = 有（多个）', highlight: '一个用 is，多个用 are', examples: [{ en: 'There is a cat on the bed.', zh: '床上有一只猫。' }, { en: 'There are three books on the desk.', zh: '桌上有三本书。' }] },
  ],
  declarative: [
    { title: '什么是陈述句？', emoji: '📄', body: '陈述句用来说明一件事，句末用句号（.）。\n分为肯定句和否定句。', highlight: '陈述句 = 告诉别人一件事', examples: [] },
    { title: '肯定句', emoji: '✅', body: '肯定句直接说"是什么"或"做什么"：', highlight: '肯定 = 正面的说法', examples: [{ en: 'I am a student.', zh: '我是学生。' }, { en: 'He likes music.', zh: '他喜欢音乐。' }, { en: 'They are happy.', zh: '他们很开心。' }] },
    { title: '否定句', emoji: '❌', body: '否定句加 not 表示"不是"或"不做"：\nam/is/are + not\ndo/does + not + 动词', highlight: '加 not 变否定！', examples: [{ en: 'I am not sad.', zh: '我不伤心。' }, { en: 'She is not tall.', zh: '她不高。' }, { en: 'I do not like fish.', zh: '我不喜欢鱼。' }] },
    { title: '缩写形式', emoji: '💡', body: 'is not = isn\'t\nare not = aren\'t\ndo not = don\'t\ndoes not = doesn\'t', highlight: '口语中常用缩写！', examples: [{ en: 'He isn\'t here.', zh: '他不在这。' }, { en: 'I don\'t know.', zh: '我不知道。' }] },
  ],
  question: [
    { title: '一般疑问句', emoji: '❓', body: '一般疑问句用 Yes 或 No 来回答。\n把 be 动词提到句首就行！', highlight: 'be 动词提前 → 疑问句', examples: [{ en: 'Are you happy?', zh: '你开心吗？' }, { en: 'Is she a teacher?', zh: '她是老师吗？' }] },
    { title: '特殊疑问句', emoji: '🔍', body: 'What = 什么   Where = 哪里\nWho = 谁     How = 怎样\nWhy = 为什么  When = 什么时候', highlight: '特殊疑问词 + be/do + 主语 + ...?', examples: [{ en: 'What is this?', zh: '这是什么？' }, { en: 'Where is my bag?', zh: '我的包在哪？' }, { en: 'Who is he?', zh: '他是谁？' }] },
    { title: 'How many...?', emoji: '🔢', body: 'How many = 多少（用于可数名词）\n后面要跟名词复数形式！', highlight: 'How many + 复数名词 + are there?', examples: [{ en: 'How many books are there?', zh: '有多少本书？' }, { en: 'How many cats do you have?', zh: '你有几只猫？' }] },
    { title: '记忆口诀', emoji: '💡', body: 'What 问"什么" Where 问"哪里"\nWho 问"谁" When 问"何时"\nWhy 问"为啥" How 问"怎样"\n六个问号小帮手！', highlight: '背下来做题不用怕！', examples: [] },
  ],
};

export const QUESTIONS_L1 = {
  pronoun: [
    Q('___ am a student.', ['I', 'He', 'She', 'You'], 0, 'am 前面只能用 I'),
    Q('___ is a girl.', ['He', 'She', 'I', 'We'], 1, 'girl(女孩)用 she'),
    Q('___ are students.', ['I', 'He', 'She', 'We'], 3, '我们 = we'),
    Q('Tom is a boy. ___ is tall.', ['He', 'She', 'I', 'We'], 0, 'Tom 是男孩，用 he'),
    Q('Lucy is my sister. ___ is nice.', ['He', 'She', 'It', 'We'], 1, 'Lucy 是女孩，用 she'),
    Q('The cat is cute. ___ is white.', ['He', 'She', 'It', 'We'], 2, '动物用 it'),
    Q('My mom and I are happy. ___ love school.', ['I', 'He', 'We', 'She'], 2, '我和妈妈 = 我们 = we'),
    Q('The dogs are big. ___ are in the park.', ['It', 'He', 'They', 'We'], 2, '那些狗 = they'),
    Q('___ am eight years old.', ['I', 'You', 'He', 'She'], 0, 'am 只跟 I'),
    Q('___ is my dad.', ['She', 'It', 'He', 'They'], 2, 'dad(爸爸)是男的'),
    Q('___ are my friends.', ['He', 'She', 'It', 'They'], 3, '朋友们(复数)用 they'),
    Q('Look at the fish! ___ is beautiful.', ['He', 'She', 'It', 'They'], 2, 'fish用 it'),
    Q('I have a brother. ___ is ten.', ['She', 'He', 'It', 'They'], 1, 'brother(哥哥)是男的'),
    Q('Amy and I like to read. ___ go to the library.', ['I', 'She', 'They', 'We'], 3, 'Amy和我 = we'),
    Q('My grandma is kind. ___ cooks well.', ['He', 'It', 'She', 'They'], 2, 'grandma(奶奶)是女的'),
  ],
  article: [
    Q('I have ___ cat.', ['a', 'an', 'the', '/'], 0, 'cat 辅音开头 → a'),
    Q('This is ___ apple.', ['a', 'an', 'the', '/'], 1, 'apple 元音开头 → an'),
    Q('I see ___ egg on the table.', ['a', 'an', 'the', '/'], 1, 'egg 元音开头 → an'),
    Q('She has ___ dog.', ['a', 'an', 'the', '/'], 0, 'dog 辅音开头 → a'),
    Q('There is ___ orange in the bag.', ['a', 'an', 'the', '/'], 1, 'orange 元音开头 → an'),
    Q('He is ___ boy.', ['a', 'an', 'the', '/'], 0, 'boy 辅音开头 → a'),
    Q('I want ___ ice cream.', ['a', 'an', 'the', '/'], 1, 'ice 元音开头 → an'),
    Q('It is ___ umbrella.', ['a', 'an', 'the', '/'], 1, 'umbrella 元音开头 → an'),
    Q('She draws ___ picture.', ['a', 'an', 'the', '/'], 0, 'picture 辅音开头 → a'),
    Q('I eat ___ banana every day.', ['a', 'an', 'the', '/'], 0, 'banana 辅音开头 → a'),
    Q('He found ___ ant.', ['a', 'an', 'the', '/'], 1, 'ant 元音开头 → an'),
    Q('There is ___ old man.', ['a', 'an', 'the', '/'], 1, 'old 元音开头 → an'),
    Q('I need ___ eraser.', ['a', 'an', 'the', '/'], 1, 'eraser 元音开头 → an'),
    Q('She is ___ English teacher.', ['a', 'an', 'the', '/'], 1, 'English 元音开头 → an'),
    Q('This is ___ elephant.', ['a', 'an', 'the', '/'], 1, 'elephant 元音开头 → an'),
  ],
  plural: [
    Q('one cat, two ___', ['cat', 'cats', 'cates', 'caties'], 1, '直接加 s → cats'),
    Q('one box, three ___', ['boxs', 'box', 'boxes', 'boxies'], 2, '以 x 结尾 → boxes'),
    Q('one dog, four ___', ['dogs', 'doges', 'dogies', 'dog'], 0, '直接加 s → dogs'),
    Q('one bus, two ___', ['buss', 'buses', 'bus', 'busis'], 1, '以 s 结尾 → buses'),
    Q('one man, three ___', ['mans', 'men', 'manes', 'menie'], 1, '特殊变化 man → men'),
    Q('one apple, five ___', ['apple', 'applees', 'apples', 'applis'], 2, '直接加 s → apples'),
    Q('one child, two ___', ['childs', 'childes', 'children', 'childies'], 2, '特殊变化 child → children'),
    Q('one book, many ___', ['bookes', 'books', 'book', 'bookies'], 1, '直接加 s → books'),
    Q('one foot, two ___', ['foots', 'feet', 'footes', 'feets'], 1, '特殊变化 foot → feet'),
    Q('one dish, two ___', ['dishs', 'dishes', 'dish', 'dishies'], 1, '以 sh 结尾 → dishes'),
    Q('one fish, three ___', ['fish', 'fishes', 'fishs', 'fishies'], 0, 'fish 单复数同形'),
    Q('one woman, two ___', ['womans', 'women', 'womanes', 'womens'], 1, '特殊变化 woman → women'),
    Q('one class, two ___', ['classs', 'classes', 'class', 'classies'], 1, '以 ss 结尾 → classes'),
    Q('one watch, two ___', ['watchs', 'watch', 'watches', 'watchies'], 2, '以 ch 结尾 → watches'),
    Q('one mouse, two ___', ['mouses', 'mice', 'mousees', 'mices'], 1, '特殊变化 mouse → mice'),
  ],
  prep: [
    Q('The ball is ___ the box. (在里面)', ['on', 'in', 'under', 'behind'], 1, 'in = 在里面'),
    Q('The book is ___ the desk. (在上面)', ['in', 'on', 'under', 'behind'], 1, 'on = 在上面'),
    Q('The cat is ___ the table. (在下面)', ['in', 'on', 'under', 'behind'], 2, 'under = 在下面'),
    Q('The dog is ___ the door. (在后面)', ['in', 'on', 'under', 'behind'], 3, 'behind = 在后面'),
    Q('The fish is ___ the water.', ['on', 'in', 'under', 'behind'], 1, '鱼在水里面 → in'),
    Q('The cup is ___ the table.', ['under', 'behind', 'in', 'on'], 3, '杯子在桌上 → on'),
    Q('The shoes are ___ the bed.', ['on', 'in', 'under', 'behind'], 2, '鞋在床下 → under'),
    Q('The picture is ___ the wall.', ['in', 'under', 'on', 'behind'], 2, '画在墙上 → on'),
    Q('The bird is ___ the cage.', ['on', 'under', 'behind', 'in'], 3, '鸟在笼子里 → in'),
    Q('Put the toy ___ the box. (放进去)', ['on', 'under', 'in', 'behind'], 2, '放进盒子里 → in'),
    Q('The apple is ___ the plate.', ['in', 'on', 'under', 'behind'], 1, '苹果在盘子上 → on'),
    Q('The flowers are ___ the vase.', ['on', 'in', 'under', 'behind'], 1, '花在花瓶里 → in'),
    Q('The hat is ___ her head.', ['in', 'on', 'under', 'behind'], 1, '帽子在头上 → on'),
    Q('The cat hides ___ the tree.', ['in', 'on', 'under', 'behind'], 3, '猫藏在树后面 → behind'),
    Q('The ball rolled ___ the table.', ['on', 'in', 'behind', 'under'], 3, '球滚到桌子下 → under'),
  ],
  beVerb: [
    Q('I ___ a student.', ['am', 'is', 'are', 'be'], 0, 'I + am'),
    Q('She ___ my sister.', ['am', 'is', 'are', 'be'], 1, 'She + is'),
    Q('They ___ happy.', ['am', 'is', 'are', 'be'], 2, 'They + are'),
    Q('He ___ tall.', ['am', 'is', 'are', 'be'], 1, 'He + is'),
    Q('We ___ friends.', ['am', 'is', 'are', 'be'], 2, 'We + are'),
    Q('You ___ kind.', ['am', 'is', 'are', 'be'], 2, 'You + are'),
    Q('It ___ a cat.', ['am', 'is', 'are', 'be'], 1, 'It + is'),
    Q('The dog ___ big.', ['am', 'is', 'are', 'be'], 1, 'The dog = it → is'),
    Q('Tom and Jerry ___ friends.', ['am', 'is', 'are', 'be'], 2, '两个人 → are'),
    Q('My mother ___ a teacher.', ['am', 'is', 'are', 'be'], 1, 'My mother = she → is'),
    Q('The books ___ on the desk.', ['am', 'is', 'are', 'be'], 2, '复数 books → are'),
    Q('___ you a student?', ['Am', 'Is', 'Are', 'Be'], 2, 'you → Are'),
    Q('___ she your sister?', ['Am', 'Is', 'Are', 'Be'], 1, 'she → Is'),
    Q('The apples ___ red.', ['am', 'is', 'are', 'be'], 2, '复数 apples → are'),
    Q('I ___ in Class Two.', ['am', 'is', 'are', 'be'], 0, 'I → am'),
  ],
  adjective: [
    Q('The elephant is very ___. 🐘', ['small', 'big', 'short', 'thin'], 1, '大象很大 → big'),
    Q('The mouse is very ___. 🐭', ['big', 'tall', 'small', 'long'], 2, '老鼠很小 → small'),
    Q('The giraffe is ___. 🦒', ['short', 'small', 'tall', 'sad'], 2, '长颈鹿很高 → tall'),
    Q('In winter, it is ___. ❄️', ['hot', 'cold', 'happy', 'new'], 1, '冬天很冷 → cold'),
    Q('In summer, it is ___. ☀️', ['cold', 'hot', 'old', 'sad'], 1, '夏天很热 → hot'),
    Q('I got 100! I am ___. 😊', ['sad', 'cold', 'happy', 'old'], 2, '很开心 → happy'),
    Q('My toy is broken. I am ___.', ['happy', 'big', 'new', 'sad'], 3, '伤心 → sad'),
    Q('The sky is ___.', ['red', 'blue', 'green', 'yellow'], 1, '天空是蓝色 → blue'),
    Q('The apple is ___.', ['blue', 'green', 'red', 'white'], 2, '苹果是红色 → red'),
    Q('The grass is ___. 🌿', ['red', 'blue', 'yellow', 'green'], 3, '草是绿色 → green'),
    Q('The ruler is ___. (长的)', ['short', 'long', 'big', 'small'], 1, '尺子很长 → long'),
    Q('The pencil is ___. (短的)', ['long', 'short', 'big', 'tall'], 1, '铅笔很短 → short'),
    Q('The opposite of "big" is ___.', ['tall', 'long', 'small', 'old'], 2, 'big 的反义词 small'),
    Q('The opposite of "happy" is ___.', ['big', 'sad', 'cold', 'new'], 1, 'happy 的反义词 sad'),
    Q('The opposite of "hot" is ___.', ['new', 'big', 'cold', 'sad'], 2, 'hot 的反义词 cold'),
  ],
  numbers: [
    Q('1 = ___', ['two', 'one', 'three', 'first'], 1, '1 = one'),
    Q('5 = ___', ['four', 'six', 'five', 'fifteen'], 2, '5 = five'),
    Q('12 = ___', ['twenty', 'eleven', 'twelve', 'ten'], 2, '12 = twelve'),
    Q('第一 = ___', ['one', 'first', 'once', 'two'], 1, '第一 = first'),
    Q('第三 = ___', ['three', 'thirteen', 'third', 'tree'], 2, '第三 = third'),
    Q('I have ___ (3) cats.', ['three', 'third', 'tree', 'thirteen'], 0, '3只猫 → three cats'),
    Q('She is ___ (8) years old.', ['eighteen', 'eighty', 'eighth', 'eight'], 3, '8岁 → eight'),
    Q('There are ___ (10) students.', ['ten', 'teen', 'tenth', 'tin'], 0, '10个 → ten'),
    Q('He is the ___ (2nd) in line.', ['two', 'twelve', 'twice', 'second'], 3, '第二 → second'),
    Q('It is the ___ (5th) day.', ['five', 'fifty', 'fifth', 'fifteen'], 2, '第五 → fifth'),
    Q('20 = ___', ['twelve', 'twenty', 'two', 'tenth'], 1, '20 = twenty'),
    Q('The ___ (1st) prize goes to Tom.', ['one', 'once', 'first', 'fast'], 2, '第一名 → first'),
    Q('15 = ___', ['fifty', 'five', 'fifteen', 'fiveteen'], 2, '15 = fifteen'),
    Q('I am in the ___ (4th) grade.', ['four', 'fourteen', 'fourth', 'for'], 2, '第四 → fourth'),
    Q('There are ___ (7) days in a week.', ['seven', 'seventeen', 'seventh', 'several'], 0, '7天 → seven'),
  ],
  sentence: [
    Q('___ is a cat.', ['This', 'These', 'Those', 'They'], 0, '这是(单数) → This is'),
    Q('___ are my books.', ['This', 'That', 'It', 'These'], 3, '这些是(复数) → These are'),
    Q('I ___ a new bag.', ['has', 'have', 'am', 'is'], 1, '我有 → I have'),
    Q('She ___ two brothers.', ['have', 'has', 'is', 'are'], 1, '她有 → She has'),
    Q('There ___ a dog in the garden.', ['are', 'is', 'am', 'have'], 1, '一只狗(单数) → There is'),
    Q('There ___ three cats on the sofa.', ['is', 'are', 'am', 'has'], 1, '三只猫(复数) → There are'),
    Q('___ is your name?', ['Where', 'What', 'Who', 'How'], 1, '你叫什么 → What'),
    Q('I ___ apples.', ['like', 'likes', 'liking', 'liked'], 0, 'I + 动词原形 → like'),
    Q('He ___ to school every day.', ['go', 'goes', 'going', 'gone'], 1, 'He + 动词三单 → goes'),
    Q('We ___ English at school.', ['studies', 'study', 'studying', 'studied'], 1, 'We + 动词原形 → study'),
    Q('___ that your teacher?', ['Are', 'Am', 'Is', 'Do'], 2, '那是(单数) → Is that'),
    Q('Tom ___ a good student.', ['are', 'am', 'is', 'be'], 2, 'Tom = he → is'),
    Q('There ___ some water in the cup.', ['is', 'are', 'am', 'have'], 0, 'water不可数 → is'),
    Q('___ is that girl?', ['What', 'Where', 'Who', 'When'], 2, '那女孩是谁 → Who'),
    Q('My father ___ a doctor.', ['are', 'am', 'is', 'be'], 2, 'My father = he → is'),
  ],
  declarative: [
    Q('把 "I am happy" 变否定句:', ['I am not happy.', 'I not am happy.', 'I happy not.', 'Not I am happy.'], 0, 'am 后加 not'),
    Q('把 "She is tall" 变否定句:', ['She not is tall.', 'She is not tall.', 'She tall not is.', 'Not she is tall.'], 1, 'is 后加 not'),
    Q('把 "They are students" 变否定句:', ['They are not students.', 'They not are students.', 'Not they are students.', 'They students not are.'], 0, 'are 后加 not'),
    Q('"I like fish" 的否定句是:', ['I not like fish.', 'I don\'t like fish.', 'I doesn\'t like fish.', 'I no like fish.'], 1, '实义动词否定用 don\'t'),
    Q('"He likes milk" 的否定句是:', ['He don\'t likes milk.', 'He not likes milk.', 'He doesn\'t like milk.', 'He doesn\'t likes milk.'], 2, '三单否定: doesn\'t + 动词原形'),
    Q('is not 的缩写是:', ['isn\'t', 'ain\'t', 'wasn\'t', 'not'], 0, 'is not = isn\'t'),
    Q('do not 的缩写是:', ['doesn\'t', 'didn\'t', 'don\'t', 'does\'t'], 2, 'do not = don\'t'),
    Q('哪个是正确的否定句?', ['She don\'t like cats.', 'She doesn\'t like cats.', 'She not like cats.', 'She no likes cats.'], 1, '三单 → doesn\'t'),
    Q('I ___ not a teacher.', ['am', 'is', 'are', 'do'], 0, 'I am not'),
    Q('We ___ not hungry.', ['am', 'is', 'are', 'does'], 2, 'We are not'),
    Q('The cat ___ not black.', ['am', 'are', 'is', 'do'], 2, 'The cat → is not'),
    Q('"aren\'t" 的完整形式是:', ['are not', 'is not', 'am not', 'do not'], 0, 'aren\'t = are not'),
    Q('哪个是肯定句?', ['I don\'t like it.', 'She isn\'t here.', 'He is happy.', 'They aren\'t coming.'], 2, '没有 not 的是肯定句'),
    Q('He ___ (not like) oranges.', ['don\'t like', 'doesn\'t like', 'isn\'t like', 'not likes'], 1, '三单否定 → doesn\'t like'),
    Q('They ___ (not be) at home.', ['isn\'t', 'doesn\'t', 'aren\'t', 'don\'t'], 2, 'They → aren\'t'),
  ],
  question: [
    Q('___ is this? — It\'s a pen.', ['Where', 'What', 'Who', 'How'], 1, '这是什么 → What'),
    Q('___ is your school? — It\'s near the park.', ['What', 'Where', 'Who', 'When'], 1, '学校在哪 → Where'),
    Q('___ is that man? — He is my dad.', ['What', 'Where', 'Who', 'When'], 2, '那人是谁 → Who'),
    Q('___ are you? — I\'m fine.', ['What', 'Where', 'How', 'Who'], 2, '你怎么样 → How'),
    Q('___ you like apples? — Yes, I do.', ['Are', 'Is', 'Do', 'Does'], 2, '一般疑问 → Do you'),
    Q('___ she like cats? — Yes, she does.', ['Are', 'Is', 'Do', 'Does'], 3, '三单一般疑问 → Does she'),
    Q('___ you a student? — Yes, I am.', ['Do', 'Does', 'Is', 'Are'], 3, 'you → Are you'),
    Q('___ books are on the desk? — Three.', ['How many', 'How much', 'What', 'Where'], 0, '多少本 → How many'),
    Q('___ old are you? — I\'m eight.', ['What', 'How', 'Where', 'Who'], 1, '几岁 → How old'),
    Q('Is this your pen? — ___', ['Yes, it is.', 'Yes, I am.', 'Yes, you are.', 'Yes, he is.'], 0, 'Is this → Yes, it is.'),
    Q('Are they happy? — No, ___', ['they isn\'t.', 'they don\'t.', 'they aren\'t.', 'they doesn\'t.'], 2, 'they → aren\'t'),
    Q('Do you like milk? — Yes, ___', ['I like.', 'I do.', 'I am.', 'I does.'], 1, 'Do → Yes, I do.'),
    Q('Does he play football? — No, ___', ['he don\'t.', 'he doesn\'t.', 'he isn\'t.', 'he not.'], 1, 'Does → No, he doesn\'t.'),
    Q('___ is your birthday? — In June.', ['What', 'Where', 'When', 'Who'], 2, '生日什么时候 → When'),
    Q('___ do you like English? — Because it\'s fun!', ['What', 'Where', 'When', 'Why'], 3, '为什么 → Why'),
  ],
};
