import TEXTBOOK_RAW from '../resources/vocabulary_tables.json';

export const TEXTBOOK_DATA = TEXTBOOK_RAW;

const TABLE_KEYS = { shizi: '识字表', xiezi: '写字表', ciyu: '词语表' };

export function getLessons(tableType) {
  const tbl = TEXTBOOK_RAW[TABLE_KEYS[tableType]];
  if (!tbl) return [];
  return Object.entries(tbl.by_lesson).map(([key, val]) => ({
    key,
    name: val.lesson_name,
    count: val.count || (val.chars ? val.chars.length : val.words ? val.words.length : 0),
  }));
}

export function getCharsForLessons(tableType, lessonKeys) {
  const tbl = TEXTBOOK_RAW[TABLE_KEYS[tableType]];
  if (!tbl) return [];
  const result = [];
  lessonKeys.forEach((lk) => {
    const lesson = tbl.by_lesson[lk];
    if (!lesson) return;
    if (tableType === 'ciyu') {
      (lesson.words || []).forEach((w) => result.push({ word: w, lesson: lk }));
    } else {
      (lesson.chars || []).forEach((c) => result.push({ ...c, lesson: lk }));
    }
  });
  return result;
}

export function getAvailableTableTypes(lessonKeys) {
  const types = [];
  ['shizi', 'xiezi', 'ciyu'].forEach((t) => {
    const items = getCharsForLessons(t, lessonKeys);
    if (items.length > 0) types.push(t);
  });
  return types;
}

const CHAR_DICT = {
  "诗": { emoji: "📜", words: [{ word: "古诗", highlight: 0 }, { word: "诗人", highlight: 0 }], meaning: "有韵律的文学作品" },
  "碧": { emoji: "💎", words: [{ word: "碧绿", highlight: 0 }, { word: "碧玉", highlight: 0 }], meaning: "青绿色" },
  "妆": { emoji: "💄", words: [{ word: "化妆", highlight: 1 }, { word: "梳妆", highlight: 1 }], meaning: "打扮装饰" },
  "绿": { emoji: "🌿", words: [{ word: "绿色", highlight: 0 }, { word: "绿叶", highlight: 0 }], meaning: "像草和树叶的颜色" },
  "丝": { emoji: "🧵", words: [{ word: "丝线", highlight: 0 }, { word: "丝绸", highlight: 0 }], meaning: "蚕吐出的细线" },
  "剪": { emoji: "✂️", words: [{ word: "剪刀", highlight: 0 }, { word: "裁剪", highlight: 1 }], meaning: "用刀或剪子割断" },
  "童": { emoji: "👦", words: [{ word: "儿童", highlight: 1 }, { word: "童话", highlight: 0 }], meaning: "小孩子" },
  "归": { emoji: "🏠", words: [{ word: "回归", highlight: 1 }, { word: "归来", highlight: 0 }], meaning: "回到原来的地方" },
  "咏": { emoji: "🎤", words: [{ word: "咏柳", highlight: 0 }, { word: "歌咏", highlight: 1 }], meaning: "用诗歌来表达" },
  "贺": { emoji: "🎉", words: [{ word: "祝贺", highlight: 1 }, { word: "贺卡", highlight: 0 }], meaning: "表示庆祝" },
  "裁": { emoji: "✂️", words: [{ word: "裁剪", highlight: 0 }, { word: "裁缝", highlight: 0 }], meaning: "用剪刀剪布" },
  "莺": { emoji: "🐦", words: [{ word: "黄莺", highlight: 1 }, { word: "莺歌", highlight: 0 }], meaning: "一种会唱歌的鸟" },
  "拂": { emoji: "🌬️", words: [{ word: "吹拂", highlight: 1 }, { word: "拂面", highlight: 0 }], meaning: "轻轻掠过" },
  "堤": { emoji: "🏞️", words: [{ word: "河堤", highlight: 1 }, { word: "堤岸", highlight: 0 }], meaning: "河边的挡水土墙" },
  "醉": { emoji: "🥴", words: [{ word: "陶醉", highlight: 1 }, { word: "醉人", highlight: 0 }], meaning: "喝酒太多迷糊了" },
  "趁": { emoji: "⏰", words: [{ word: "趁早", highlight: 0 }, { word: "趁机", highlight: 0 }], meaning: "利用时间或机会" },
  "脱": { emoji: "👕", words: [{ word: "脱衣", highlight: 0 }, { word: "脱掉", highlight: 0 }], meaning: "把穿着的东西取下来" },
  "袄": { emoji: "🧥", words: [{ word: "棉袄", highlight: 1 }, { word: "袄子", highlight: 0 }], meaning: "有衬里的上衣" },
  "遮": { emoji: "☂️", words: [{ word: "遮挡", highlight: 0 }, { word: "遮盖", highlight: 0 }], meaning: "挡住，盖住" },
  "掩": { emoji: "🙈", words: [{ word: "掩护", highlight: 0 }, { word: "掩盖", highlight: 0 }], meaning: "遮盖起来" },
  "探": { emoji: "🔍", words: [{ word: "探索", highlight: 0 }, { word: "探头", highlight: 0 }], meaning: "伸出头来看" },
  "嫩": { emoji: "🌱", words: [{ word: "嫩芽", highlight: 0 }, { word: "嫩绿", highlight: 0 }], meaning: "刚长出来的，柔软的" },
  "符": { emoji: "🎵", words: [{ word: "符号", highlight: 0 }, { word: "音符", highlight: 1 }], meaning: "标记或记号" },
  "触": { emoji: "👆", words: [{ word: "触摸", highlight: 0 }, { word: "接触", highlight: 1 }], meaning: "碰到，接触到" },
  "鹊": { emoji: "🐦", words: [{ word: "喜鹊", highlight: 1 }, { word: "鹊桥", highlight: 0 }], meaning: "一种黑白相间的鸟" },
  "邮": { emoji: "📮", words: [{ word: "邮票", highlight: 0 }, { word: "邮递", highlight: 0 }], meaning: "寄送信件" },
  "递": { emoji: "📬", words: [{ word: "传递", highlight: 1 }, { word: "邮递", highlight: 1 }], meaning: "传送给别人" },
  "村": { emoji: "🏘️", words: [{ word: "农村", highlight: 1 }, { word: "村庄", highlight: 0 }], meaning: "乡下的地方" },
  "笋": { emoji: "🎍", words: [{ word: "竹笋", highlight: 1 }, { word: "笋芽", highlight: 0 }], meaning: "竹子刚长出来的嫩茎" },
  "芽": { emoji: "🌱", words: [{ word: "发芽", highlight: 1 }, { word: "嫩芽", highlight: 1 }], meaning: "植物刚长出来的小苗" },
  "唤": { emoji: "📢", words: [{ word: "呼唤", highlight: 1 }, { word: "唤醒", highlight: 0 }], meaning: "叫喊" },
  "揉": { emoji: "🤲", words: [{ word: "揉眼", highlight: 0 }, { word: "揉搓", highlight: 0 }], meaning: "用手来回搓" },
  "漆": { emoji: "🎨", words: [{ word: "油漆", highlight: 1 }, { word: "漆黑", highlight: 0 }], meaning: "涂料；很黑" },
  "轰": { emoji: "💥", words: [{ word: "轰隆", highlight: 0 }, { word: "轰炸", highlight: 0 }], meaning: "很大的声音" },
  "扭": { emoji: "🔄", words: [{ word: "扭动", highlight: 0 }, { word: "扭头", highlight: 0 }], meaning: "转动身体" },
  "钻": { emoji: "⛏️", words: [{ word: "钻进", highlight: 0 }, { word: "钻研", highlight: 0 }], meaning: "穿过，进入" },
  "辫": { emoji: "👧", words: [{ word: "辫子", highlight: 0 }, { word: "编辫", highlight: 1 }], meaning: "编成的头发" },
  "雷": { emoji: "⚡", words: [{ word: "打雷", highlight: 1 }, { word: "雷声", highlight: 0 }], meaning: "天上发出的轰隆声" },
  "冈": { emoji: "⛰️", words: [{ word: "山冈", highlight: 1 }, { word: "景阳冈", highlight: 2 }], meaning: "不太高的山" },
  "世": { emoji: "🌍", words: [{ word: "世界", highlight: 0 }, { word: "世纪", highlight: 0 }], meaning: "整个地球" },
  "界": { emoji: "🗺️", words: [{ word: "世界", highlight: 1 }, { word: "边界", highlight: 1 }], meaning: "范围或限制" },
  "轿": { emoji: "🚗", words: [{ word: "轿车", highlight: 0 }, { word: "花轿", highlight: 1 }], meaning: "一种交通工具" },
  "哈": { emoji: "😄", words: [{ word: "哈哈", highlight: 0 }, { word: "笑哈哈", highlight: 1 }], meaning: "笑声" },
  "股": { emoji: "💨", words: [{ word: "一股", highlight: 1 }, { word: "股票", highlight: 0 }], meaning: "一阵，一份" },
  "愤": { emoji: "😠", words: [{ word: "愤怒", highlight: 0 }, { word: "气愤", highlight: 1 }], meaning: "生气" },
  "喷": { emoji: "🌊", words: [{ word: "喷水", highlight: 0 }, { word: "喷泉", highlight: 0 }], meaning: "液体急速射出" },
  "弓": { emoji: "🏹", words: [{ word: "弓箭", highlight: 0 }, { word: "弹弓", highlight: 1 }], meaning: "射箭的工具" },
  "箭": { emoji: "🏹", words: [{ word: "弓箭", highlight: 1 }, { word: "火箭", highlight: 1 }], meaning: "用弓射出的武器" },
  "值": { emoji: "💰", words: [{ word: "值日", highlight: 0 }, { word: "价值", highlight: 1 }], meaning: "有用的，轮到做事" },
  "泡": { emoji: "🫧", words: [{ word: "泡泡", highlight: 0 }, { word: "水泡", highlight: 1 }], meaning: "水中的小球" },
  "饱": { emoji: "😋", words: [{ word: "吃饱", highlight: 1 }, { word: "饱满", highlight: 0 }], meaning: "吃够了" },
  "晓": { emoji: "🌅", words: [{ word: "知晓", highlight: 1 }, { word: "春晓", highlight: 1 }], meaning: "天刚亮的时候" },
  "慈": { emoji: "🤱", words: [{ word: "慈母", highlight: 0 }, { word: "慈祥", highlight: 0 }], meaning: "和善慈爱的" },
  "毕": { emoji: "🎓", words: [{ word: "毕竟", highlight: 0 }, { word: "毕业", highlight: 0 }], meaning: "完成" },
  "竟": { emoji: "❗", words: [{ word: "毕竟", highlight: 1 }, { word: "竟然", highlight: 0 }], meaning: "终于，居然" },
  "映": { emoji: "🌅", words: [{ word: "放映", highlight: 1 }, { word: "映照", highlight: 0 }], meaning: "照射，反射" },
  "寺": { emoji: "🏯", words: [{ word: "寺庙", highlight: 0 }, { word: "古寺", highlight: 1 }], meaning: "佛教的建筑" },
  "含": { emoji: "🤐", words: [{ word: "包含", highlight: 1 }, { word: "含义", highlight: 0 }], meaning: "嘴里放着，包括" },
  "窗": { emoji: "🪟", words: [{ word: "窗户", highlight: 0 }, { word: "窗台", highlight: 0 }], meaning: "墙上透光的洞" },
  "岭": { emoji: "🏔️", words: [{ word: "山岭", highlight: 1 }, { word: "岭南", highlight: 0 }], meaning: "连绵的山" },
  "鸣": { emoji: "🐦", words: [{ word: "鸟鸣", highlight: 1 }, { word: "鸣叫", highlight: 0 }], meaning: "鸟叫" },
  "绝": { emoji: "🔥", words: [{ word: "绝对", highlight: 0 }, { word: "绝妙", highlight: 0 }], meaning: "完全的，极好的" },
  "烟": { emoji: "💨", words: [{ word: "烟花", highlight: 0 }, { word: "香烟", highlight: 1 }], meaning: "燃烧产生的气体" },
  "话": { emoji: "💬", words: [{ word: "说话", highlight: 1 }, { word: "电话", highlight: 1 }], meaning: "用嘴说出来的语言" },
  "朗": { emoji: "📖", words: [{ word: "朗读", highlight: 0 }, { word: "开朗", highlight: 1 }], meaning: "声音清楚响亮" },
  "题": { emoji: "📝", words: [{ word: "题目", highlight: 0 }, { word: "问题", highlight: 1 }], meaning: "需要回答的问题" },
  "桩": { emoji: "🪵", words: [{ word: "树桩", highlight: 1 }, { word: "木桩", highlight: 1 }], meaning: "打进地里的柱子" },
  "肥": { emoji: "🐷", words: [{ word: "肥胖", highlight: 0 }, { word: "肥料", highlight: 0 }], meaning: "身体很胖" },
  "鲜": { emoji: "🌸", words: [{ word: "鲜花", highlight: 0 }, { word: "新鲜", highlight: 1 }], meaning: "新鲜的，好看的" },
  "邻": { emoji: "🏘️", words: [{ word: "邻居", highlight: 0 }, { word: "相邻", highlight: 1 }], meaning: "住在旁边的人" },
  "程": { emoji: "🛤️", words: [{ word: "路程", highlight: 1 }, { word: "工程", highlight: 1 }], meaning: "路途，过程" },
  "魔": { emoji: "🧙", words: [{ word: "魔术", highlight: 0 }, { word: "魔法", highlight: 0 }], meaning: "神奇的法术" },
  "术": { emoji: "🎭", words: [{ word: "美术", highlight: 1 }, { word: "技术", highlight: 1 }], meaning: "技艺，方法" },
  "食": { emoji: "🍜", words: [{ word: "食物", highlight: 0 }, { word: "美食", highlight: 1 }], meaning: "吃的东西" },
  "烤": { emoji: "🍗", words: [{ word: "烤鸭", highlight: 0 }, { word: "烧烤", highlight: 1 }], meaning: "用火加热" },
  "茄": { emoji: "🍆", words: [{ word: "茄子", highlight: 0 }, { word: "番茄", highlight: 1 }], meaning: "一种紫色的蔬菜" },
  "炒": { emoji: "🍳", words: [{ word: "炒菜", highlight: 0 }, { word: "炒饭", highlight: 0 }], meaning: "用锅加油翻炒食物" },
  "煮": { emoji: "🥘", words: [{ word: "煮饭", highlight: 0 }, { word: "水煮", highlight: 1 }], meaning: "放在水里加热" },
  "贝": { emoji: "🐚", words: [{ word: "贝壳", highlight: 0 }, { word: "宝贝", highlight: 1 }], meaning: "海里的壳类动物" },
  "壳": { emoji: "🐚", words: [{ word: "贝壳", highlight: 1 }, { word: "蛋壳", highlight: 1 }], meaning: "外面的硬皮" },
  "甲": { emoji: "🛡️", words: [{ word: "甲骨文", highlight: 0 }, { word: "指甲", highlight: 1 }], meaning: "第一，盔甲" },
  "币": { emoji: "💰", words: [{ word: "钱币", highlight: 1 }, { word: "硬币", highlight: 1 }], meaning: "钱" },
  "财": { emoji: "💰", words: [{ word: "发财", highlight: 1 }, { word: "财宝", highlight: 0 }], meaning: "钱和物品" },
  "赚": { emoji: "💵", words: [{ word: "赚钱", highlight: 0 }, { word: "赚到", highlight: 0 }], meaning: "得到钱" },
  "赔": { emoji: "💸", words: [{ word: "赔钱", highlight: 0 }, { word: "赔偿", highlight: 0 }], meaning: "付出钱做补偿" },
  "购": { emoji: "🛒", words: [{ word: "购买", highlight: 0 }, { word: "采购", highlight: 1 }], meaning: "买东西" },
  "贫": { emoji: "😢", words: [{ word: "贫穷", highlight: 0 }, { word: "贫困", highlight: 0 }], meaning: "很穷" },
  "彩": { emoji: "🌈", words: [{ word: "彩色", highlight: 0 }, { word: "彩虹", highlight: 0 }], meaning: "多种颜色" },
  "梦": { emoji: "💭", words: [{ word: "做梦", highlight: 1 }, { word: "梦想", highlight: 0 }], meaning: "睡觉时的想象" },
  "森": { emoji: "🌲", words: [{ word: "森林", highlight: 0 }, { word: "森森", highlight: 0 }], meaning: "很多树木" },
  "拉": { emoji: "🤝", words: [{ word: "拉手", highlight: 0 }, { word: "拉住", highlight: 0 }], meaning: "用力把东西靠近" },
  "结": { emoji: "🎀", words: [{ word: "结果", highlight: 0 }, { word: "打结", highlight: 1 }], meaning: "系上；最后" },
  "掰": { emoji: "🤲", words: [{ word: "掰开", highlight: 0 }, { word: "掰断", highlight: 0 }], meaning: "用手分开" },
  "摘": { emoji: "🍎", words: [{ word: "摘花", highlight: 0 }, { word: "摘下", highlight: 0 }], meaning: "把长着的东西取下来" },
  "伯": { emoji: "👴", words: [{ word: "伯伯", highlight: 0 }, { word: "大伯", highlight: 1 }], meaning: "爸爸的哥哥" },
  "匹": { emoji: "🐴", words: [{ word: "一匹马", highlight: 1 }, { word: "匹配", highlight: 0 }], meaning: "量词，用于马" },
  "纹": { emoji: "🌊", words: [{ word: "花纹", highlight: 1 }, { word: "波纹", highlight: 1 }], meaning: "表面的线条" },
  "恋": { emoji: "❤️", words: [{ word: "留恋", highlight: 1 }, { word: "恋恋不舍", highlight: 0 }], meaning: "舍不得" },
  "舍": { emoji: "🏠", words: [{ word: "舍不得", highlight: 0 }, { word: "宿舍", highlight: 1 }], meaning: "放弃；房子" },
  "求": { emoji: "🙏", words: [{ word: "请求", highlight: 1 }, { word: "要求", highlight: 1 }], meaning: "请别人帮忙" },
  "仍": { emoji: "🔁", words: [{ word: "仍然", highlight: 0 }, { word: "仍旧", highlight: 0 }], meaning: "还是，依然" },
  "柴": { emoji: "🪵", words: [{ word: "柴火", highlight: 0 }, { word: "砍柴", highlight: 1 }], meaning: "可以燃烧的木头" },
  "烧": { emoji: "🔥", words: [{ word: "烧火", highlight: 0 }, { word: "燃烧", highlight: 1 }], meaning: "用火加热" },
  "旺": { emoji: "🔥", words: [{ word: "旺盛", highlight: 0 }, { word: "兴旺", highlight: 1 }], meaning: "火大，很兴盛" },
  "渐": { emoji: "📈", words: [{ word: "渐渐", highlight: 0 }, { word: "逐渐", highlight: 1 }], meaning: "慢慢地" },
  "哎": { emoji: "😯", words: [{ word: "哎呀", highlight: 0 }, { word: "哎哟", highlight: 0 }], meaning: "表示惊讶的语气词" },
  "冒": { emoji: "💨", words: [{ word: "冒险", highlight: 0 }, { word: "冒出", highlight: 0 }], meaning: "向外出来" },
  "烫": { emoji: "♨️", words: [{ word: "烫手", highlight: 0 }, { word: "滚烫", highlight: 1 }], meaning: "温度很高" },
  "终": { emoji: "🏁", words: [{ word: "终于", highlight: 0 }, { word: "终点", highlight: 0 }], meaning: "最后" },
  "于": { emoji: "📌", words: [{ word: "终于", highlight: 1 }, { word: "由于", highlight: 1 }], meaning: "在，对于" },
  "吐": { emoji: "😛", words: [{ word: "吞吐", highlight: 1 }, { word: "吐出", highlight: 0 }], meaning: "从嘴里出来" },
  "蚕": { emoji: "🐛", words: [{ word: "蚕宝宝", highlight: 0 }, { word: "养蚕", highlight: 1 }], meaning: "会吐丝的虫子" },
  "桑": { emoji: "🌳", words: [{ word: "桑叶", highlight: 0 }, { word: "桑树", highlight: 0 }], meaning: "蚕吃的叶子的树" },
  "盖": { emoji: "🧢", words: [{ word: "盖子", highlight: 0 }, { word: "盖上", highlight: 0 }], meaning: "覆盖上面" },
  "挡": { emoji: "🛡️", words: [{ word: "阻挡", highlight: 1 }, { word: "挡住", highlight: 0 }], meaning: "拦住" },
  "凶": { emoji: "😡", words: [{ word: "凶猛", highlight: 0 }, { word: "凶恶", highlight: 0 }], meaning: "很厉害很可怕" },
  "猛": { emoji: "🐯", words: [{ word: "凶猛", highlight: 1 }, { word: "猛烈", highlight: 0 }], meaning: "力量很大" },
  "补": { emoji: "🧵", words: [{ word: "补丁", highlight: 0 }, { word: "补充", highlight: 0 }], meaning: "把破的地方修好" },
  "充": { emoji: "🔋", words: [{ word: "充满", highlight: 0 }, { word: "充电", highlight: 0 }], meaning: "装满" },
  "抢": { emoji: "🏃", words: [{ word: "抢先", highlight: 0 }, { word: "抢救", highlight: 0 }], meaning: "用力夺取" },
  "助": { emoji: "🤝", words: [{ word: "帮助", highlight: 1 }, { word: "助手", highlight: 0 }], meaning: "帮别人做事" },
  "筝": { emoji: "🪁", words: [{ word: "风筝", highlight: 1 }, { word: "古筝", highlight: 1 }], meaning: "风筝；一种乐器" },
  "鼠": { emoji: "🐭", words: [{ word: "老鼠", highlight: 1 }, { word: "松鼠", highlight: 1 }], meaning: "小动物" },
  "蜘": { emoji: "🕷️", words: [{ word: "蜘蛛", highlight: 0 }], meaning: "会织网的虫子" },
  "蛛": { emoji: "🕸️", words: [{ word: "蜘蛛", highlight: 1 }], meaning: "蜘蛛的蛛" },
  "网": { emoji: "🕸️", words: [{ word: "蜘蛛网", highlight: 2 }, { word: "上网", highlight: 1 }], meaning: "用线编成的东西" },
  "店": { emoji: "🏪", words: [{ word: "商店", highlight: 1 }, { word: "书店", highlight: 1 }], meaning: "卖东西的地方" },
  "蹲": { emoji: "🧎", words: [{ word: "蹲下", highlight: 0 }], meaning: "弯着腿坐低" },
  "寂": { emoji: "🤫", words: [{ word: "寂寞", highlight: 0 }, { word: "寂静", highlight: 0 }], meaning: "安静，孤单" },
  "寞": { emoji: "😔", words: [{ word: "寂寞", highlight: 1 }], meaning: "孤单寂寞" },
  "编": { emoji: "📚", words: [{ word: "编织", highlight: 0 }, { word: "编写", highlight: 0 }], meaning: "把东西组织起来" },
  "织": { emoji: "🧶", words: [{ word: "编织", highlight: 1 }, { word: "织布", highlight: 0 }], meaning: "用线做成布" },
  "困": { emoji: "😴", words: [{ word: "困难", highlight: 0 }, { word: "困倦", highlight: 0 }], meaning: "感到难做或想睡" },
  "湾": { emoji: "🏖️", words: [{ word: "台湾", highlight: 1 }, { word: "海湾", highlight: 1 }], meaning: "海岸弯曲的地方" },
  "峡": { emoji: "🏞️", words: [{ word: "海峡", highlight: 1 }, { word: "三峡", highlight: 1 }], meaning: "两山之间的水道" },
  "族": { emoji: "👨‍👩‍👧‍👦", words: [{ word: "民族", highlight: 1 }, { word: "家族", highlight: 1 }], meaning: "一群有相同文化的人" },
  "谊": { emoji: "🤝", words: [{ word: "友谊", highlight: 1 }], meaning: "朋友之间的感情" },
  "齐": { emoji: "🧹", words: [{ word: "整齐", highlight: 1 }, { word: "齐全", highlight: 0 }], meaning: "排列均匀" },
  "奋": { emoji: "💪", words: [{ word: "勤奋", highlight: 1 }, { word: "奋斗", highlight: 0 }], meaning: "努力向上" },
  "繁": { emoji: "🌸", words: [{ word: "繁忙", highlight: 0 }, { word: "繁荣", highlight: 0 }], meaning: "很多很复杂" },
  "荣": { emoji: "🏆", words: [{ word: "光荣", highlight: 1 }, { word: "繁荣", highlight: 1 }], meaning: "有光彩" },
  "传": { emoji: "📨", words: [{ word: "传说", highlight: 0 }, { word: "传递", highlight: 0 }], meaning: "从一个传到另一个" },
  "统": { emoji: "🔗", words: [{ word: "传统", highlight: 1 }, { word: "统一", highlight: 0 }], meaning: "一直延续下来的" },
  "锋": { emoji: "🗡️", words: [{ word: "雷锋", highlight: 1 }, { word: "锋利", highlight: 0 }], meaning: "尖锐的，人名" },
  "叔": { emoji: "👨", words: [{ word: "叔叔", highlight: 0 }, { word: "大叔", highlight: 1 }], meaning: "爸爸的弟弟" },
  "曾": { emoji: "🕰️", words: [{ word: "曾经", highlight: 0 }], meaning: "从前，以前" },
  "泥": { emoji: "🏗️", words: [{ word: "泥土", highlight: 0 }, { word: "水泥", highlight: 1 }], meaning: "湿的土" },
  "泞": { emoji: "🌧️", words: [{ word: "泥泞", highlight: 1 }], meaning: "路上有很多泥水" },
  "荆": { emoji: "🌿", words: [{ word: "荆棘", highlight: 0 }], meaning: "带刺的灌木" },
  "棘": { emoji: "🌵", words: [{ word: "荆棘", highlight: 1 }], meaning: "植物的刺" },
  "瓣": { emoji: "🌸", words: [{ word: "花瓣", highlight: 1 }, { word: "瓣膜", highlight: 0 }], meaning: "花朵的一片" },
  "莲": { emoji: "🪷", words: [{ word: "莲花", highlight: 0 }, { word: "莲藕", highlight: 0 }], meaning: "水里长的花" },
  "蓬": { emoji: "🌿", words: [{ word: "蓬松", highlight: 0 }, { word: "莲蓬", highlight: 1 }], meaning: "松散的样子" },
  "露": { emoji: "💧", words: [{ word: "露水", highlight: 0 }, { word: "露出", highlight: 0 }], meaning: "水珠；显出来" },
  "角": { emoji: "🦌", words: [{ word: "角落", highlight: 0 }, { word: "牛角", highlight: 1 }], meaning: "尖尖的突出部分" },
  "躺": { emoji: "🛏️", words: [{ word: "躺下", highlight: 0 }, { word: "躺着", highlight: 0 }], meaning: "平平地卧着" },
  "晶": { emoji: "💎", words: [{ word: "水晶", highlight: 1 }, { word: "亮晶晶", highlight: 1 }], meaning: "透明闪亮的" },
  "停": { emoji: "🛑", words: [{ word: "停下", highlight: 0 }, { word: "停车", highlight: 0 }], meaning: "不动了" },
  "甘": { emoji: "🍯", words: [{ word: "甘甜", highlight: 0 }, { word: "甘心", highlight: 0 }], meaning: "甜的" },
  "罗": { emoji: "🎪", words: [{ word: "罗列", highlight: 0 }, { word: "罗马", highlight: 0 }], meaning: "排列" },
  "亭": { emoji: "⛩️", words: [{ word: "凉亭", highlight: 1 }, { word: "亭子", highlight: 0 }], meaning: "有顶无墙的建筑" },
  "般": { emoji: "🔄", words: [{ word: "一般", highlight: 1 }, { word: "般配", highlight: 0 }], meaning: "种类" },
  "精": { emoji: "✨", words: [{ word: "精彩", highlight: 0 }, { word: "精神", highlight: 0 }], meaning: "很好的，仔细的" },
  "糊": { emoji: "🍲", words: [{ word: "糊涂", highlight: 0 }, { word: "模糊", highlight: 1 }], meaning: "不清楚" },
  "尤": { emoji: "⭐", words: [{ word: "尤其", highlight: 0 }, { word: "尤为", highlight: 0 }], meaning: "特别" },
  "其": { emoji: "👉", words: [{ word: "其他", highlight: 0 }, { word: "尤其", highlight: 1 }], meaning: "那个，他的" },
  "仙": { emoji: "🧚", words: [{ word: "神仙", highlight: 1 }, { word: "仙女", highlight: 0 }], meaning: "神话中的人" },
  "塔": { emoji: "🗼", words: [{ word: "宝塔", highlight: 1 }, { word: "灯塔", highlight: 1 }], meaning: "很高的建筑" },
  "形": { emoji: "🔷", words: [{ word: "形状", highlight: 0 }, { word: "图形", highlight: 1 }], meaning: "样子" },
  "状": { emoji: "📋", words: [{ word: "形状", highlight: 1 }, { word: "状态", highlight: 0 }], meaning: "样子，情况" },
  "雾": { emoji: "🌫️", words: [{ word: "大雾", highlight: 1 }, { word: "雾气", highlight: 0 }], meaning: "看不清的水汽" },
  "蒙": { emoji: "🙈", words: [{ word: "蒙蒙", highlight: 0 }, { word: "启蒙", highlight: 1 }], meaning: "遮盖住" },
  "景": { emoji: "🏞️", words: [{ word: "风景", highlight: 1 }, { word: "景色", highlight: 0 }], meaning: "看到的样子" },
  "省": { emoji: "🗺️", words: [{ word: "省份", highlight: 0 }, { word: "省心", highlight: 0 }], meaning: "行政区域" },
  "茂": { emoji: "🌳", words: [{ word: "茂盛", highlight: 0 }, { word: "茂密", highlight: 0 }], meaning: "植物长得好" },
  "盛": { emoji: "🌺", words: [{ word: "盛开", highlight: 0 }, { word: "茂盛", highlight: 1 }], meaning: "兴旺，多" },
  "隐": { emoji: "🙈", words: [{ word: "隐藏", highlight: 0 }, { word: "隐约", highlight: 0 }], meaning: "藏起来" },
  "约": { emoji: "📅", words: [{ word: "大约", highlight: 1 }, { word: "约定", highlight: 0 }], meaning: "差不多，约定" },
  "环": { emoji: "💍", words: [{ word: "环绕", highlight: 0 }, { word: "环境", highlight: 0 }], meaning: "圆圈" },
  "绕": { emoji: "🔄", words: [{ word: "环绕", highlight: 1 }, { word: "围绕", highlight: 1 }], meaning: "转圈" },
  "恋": { emoji: "❤️", words: [{ word: "留恋", highlight: 1 }, { word: "恋恋不舍", highlight: 0 }], meaning: "舍不得离开" },
};

export function getWordInfo(char) {
  if (CHAR_DICT[char]) return CHAR_DICT[char];
  return { emoji: "📝", words: [{ word: char, highlight: 0 }], meaning: `学习"${char}"` };
}

const DICTATION_XIEZI = {
  "诗": { contextWord: "古诗", contextPhrase: "古诗的诗" },
  "碧": { contextWord: "碧绿", contextPhrase: "碧绿的碧" },
  "妆": { contextWord: "化妆", contextPhrase: "化妆的妆" },
  "绿": { contextWord: "绿色", contextPhrase: "绿色的绿" },
  "丝": { contextWord: "丝线", contextPhrase: "丝线的丝" },
  "剪": { contextWord: "剪刀", contextPhrase: "剪刀的剪" },
  "童": { contextWord: "儿童", contextPhrase: "儿童的童" },
  "归": { contextWord: "回归", contextPhrase: "回归的归" },
  "话": { contextWord: "说话", contextPhrase: "说话的话" },
  "朗": { contextWord: "朗读", contextPhrase: "朗读的朗" },
  "题": { contextWord: "题目", contextPhrase: "题目的题" },
  "桩": { contextWord: "木桩", contextPhrase: "木桩的桩" },
  "肥": { contextWord: "肥胖", contextPhrase: "肥胖的肥" },
  "鲜": { contextWord: "新鲜", contextPhrase: "新鲜的鲜" },
  "邻": { contextWord: "邻居", contextPhrase: "邻居的邻" },
  "程": { contextWord: "路程", contextPhrase: "路程的程" },
  "魔": { contextWord: "魔术", contextPhrase: "魔术的魔" },
  "术": { contextWord: "美术", contextPhrase: "美术的术" },
  "食": { contextWord: "食物", contextPhrase: "食物的食" },
  "烤": { contextWord: "烤鸭", contextPhrase: "烤鸭的烤" },
  "茄": { contextWord: "茄子", contextPhrase: "茄子的茄" },
  "炒": { contextWord: "炒菜", contextPhrase: "炒菜的炒" },
  "煮": { contextWord: "煮饭", contextPhrase: "煮饭的煮" },
  "贝": { contextWord: "宝贝", contextPhrase: "宝贝的贝" },
  "壳": { contextWord: "贝壳", contextPhrase: "贝壳的壳" },
  "甲": { contextWord: "指甲", contextPhrase: "指甲的甲" },
  "币": { contextWord: "硬币", contextPhrase: "硬币的币" },
  "财": { contextWord: "财宝", contextPhrase: "财宝的财" },
  "彩": { contextWord: "彩色", contextPhrase: "彩色的彩" },
  "梦": { contextWord: "做梦", contextPhrase: "做梦的梦" },
  "森": { contextWord: "森林", contextPhrase: "森林的森" },
  "拉": { contextWord: "拉手", contextPhrase: "拉手的拉" },
  "结": { contextWord: "结果", contextPhrase: "结果的结" },
  "掰": { contextWord: "掰开", contextPhrase: "掰开的掰" },
  "摘": { contextWord: "摘花", contextPhrase: "摘花的摘" },
  "伯": { contextWord: "伯伯", contextPhrase: "伯伯的伯" },
  "匹": { contextWord: "一匹马", contextPhrase: "一匹马的匹" },
  "纹": { contextWord: "花纹", contextPhrase: "花纹的纹" },
  "补": { contextWord: "补丁", contextPhrase: "补丁的补" },
  "充": { contextWord: "充满", contextPhrase: "充满的充" },
  "助": { contextWord: "帮助", contextPhrase: "帮助的助" },
  "筝": { contextWord: "风筝", contextPhrase: "风筝的筝" },
  "湾": { contextWord: "台湾", contextPhrase: "台湾的湾" },
  "峡": { contextWord: "海峡", contextPhrase: "海峡的峡" },
  "族": { contextWord: "民族", contextPhrase: "民族的族" },
  "谊": { contextWord: "友谊", contextPhrase: "友谊的谊" },
  "齐": { contextWord: "整齐", contextPhrase: "整齐的齐" },
  "奋": { contextWord: "勤奋", contextPhrase: "勤奋的奋" },
  "繁": { contextWord: "繁忙", contextPhrase: "繁忙的繁" },
  "荣": { contextWord: "光荣", contextPhrase: "光荣的荣" },
  "传": { contextWord: "传说", contextPhrase: "传说的传" },
  "统": { contextWord: "传统", contextPhrase: "传统的统" },
  "锋": { contextWord: "雷锋", contextPhrase: "雷锋的锋" },
  "叔": { contextWord: "叔叔", contextPhrase: "叔叔的叔" },
  "泥": { contextWord: "泥土", contextPhrase: "泥土的泥" },
  "瓣": { contextWord: "花瓣", contextPhrase: "花瓣的瓣" },
  "莲": { contextWord: "莲花", contextPhrase: "莲花的莲" },
  "露": { contextWord: "露水", contextPhrase: "露水的露" },
  "角": { contextWord: "角落", contextPhrase: "角落的角" },
  "晶": { contextWord: "水晶", contextPhrase: "水晶的晶" },
  "停": { contextWord: "停下", contextPhrase: "停下的停" },
  "亭": { contextWord: "凉亭", contextPhrase: "凉亭的亭" },
  "精": { contextWord: "精彩", contextPhrase: "精彩的精" },
  "仙": { contextWord: "神仙", contextPhrase: "神仙的仙" },
  "塔": { contextWord: "宝塔", contextPhrase: "宝塔的塔" },
  "雾": { contextWord: "大雾", contextPhrase: "大雾的雾" },
  "景": { contextWord: "风景", contextPhrase: "风景的景" },
};

const DICTATION_CIYU = {
  "春天": { contextSentence: "春天来了的春天" },
  "寻找": { contextSentence: "寻找春天的寻找" },
  "眉毛": { contextSentence: "弯弯的眉毛的眉毛" },
  "野花": { contextSentence: "山上的野花的野花" },
  "柳枝": { contextSentence: "柳枝发芽的柳枝" },
  "桃花": { contextSentence: "粉红的桃花的桃花" },
  "鲜花": { contextSentence: "美丽的鲜花的鲜花" },
  "先生": { contextSentence: "老先生好的先生" },
  "原来": { contextSentence: "原来如此的原来" },
  "大叔": { contextSentence: "大叔你好的大叔" },
  "太太": { contextSentence: "太太好的太太" },
  "做客": { contextSentence: "去朋友家做客的做客" },
  "惊奇": { contextSentence: "非常惊奇的惊奇" },
  "快活": { contextSentence: "快活地玩的快活" },
  "美好": { contextSentence: "美好的一天的美好" },
  "礼物": { contextSentence: "收到礼物的礼物" },
  "植树": { contextSentence: "一起植树的植树" },
  "故事": { contextSentence: "讲故事的故事" },
  "生活": { contextSentence: "幸福生活的生活" },
  "美食": { contextSentence: "好吃的美食的美食" },
  "茄子": { contextSentence: "紫色的茄子的茄子" },
  "烤鸭": { contextSentence: "北京烤鸭的烤鸭" },
  "羊肉": { contextSentence: "好吃的羊肉的羊肉" },
  "蛋炒饭": { contextSentence: "一碗蛋炒饭的蛋炒饭" },
  "钱币": { contextSentence: "古代钱币的钱币" },
  "钱财": { contextSentence: "钱财宝贝的钱财" },
  "有关": { contextSentence: "有关联的有关" },
  "样子": { contextSentence: "好看的样子的样子" },
  "甲骨文": { contextSentence: "古代甲骨文的甲骨文" },
  "水煮鱼": { contextSentence: "好吃的水煮鱼的水煮鱼" },
  "碧空如洗": { contextSentence: "碧空如洗万里无云的碧空如洗" },
  "万里无云": { contextSentence: "万里无云的万里无云" },
  "动物": { contextSentence: "可爱的动物的动物" },
  "新奇": { contextSentence: "新奇有趣的新奇" },
  "市场": { contextSentence: "去市场买菜的市场" },
  "夺目": { contextSentence: "光彩夺目的夺目" },
  "力量": { contextSentence: "力量很大的力量" },
  "微笑": { contextSentence: "甜甜的微笑的微笑" },
  "古迹": { contextSentence: "名胜古迹的古迹" },
  "传统": { contextSentence: "传统文化的传统" },
  "节日": { contextSentence: "欢乐的节日的节日" },
  "团圆": { contextSentence: "一家团圆的团圆" },
  "热闹": { contextSentence: "非常热闹的热闹" },
  "指南针": { contextSentence: "神奇的指南针的指南针" },
  "造纸术": { contextSentence: "古代的造纸术的造纸术" },
};

export function getDictationContext(tableType, item) {
  if (tableType === 'xiezi') {
    const c = item.char || item;
    const entry = DICTATION_XIEZI[c];
    if (entry) return entry;
    const info = getWordInfo(c);
    const firstWord = info.words[0]?.word || c;
    return { contextWord: firstWord, contextPhrase: `${firstWord}的${c}` };
  }
  if (tableType === 'ciyu') {
    const w = item.word || item;
    const entry = DICTATION_CIYU[w];
    if (entry) return entry;
    return { contextSentence: `${w}的${w}` };
  }
  return { contextWord: item.char || item, contextPhrase: item.char || item };
}

export const TABLE_TYPE_LABELS = {
  shizi: '识字表',
  xiezi: '写字表',
  ciyu: '词语表',
};
