import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const chars = `橡 枪 控 坦 克 航 模 型 寓 则 亡 牢 圈 叼 修 堵 悔 实 焦 筋 喘 费 截 室 而 幅 审 肃 晌 嘻 悦 诲 棚 驮 坊 浅 刚 淹 哩 叹 唉 蹄 既 厨 柜 厢 商 厦 洞 穴 窟 窿 窖 窄 甫 泊 净 宋 压 蝉 响 哗 慌 针 辨 忠 导 盏 永 闯 碰 稠 稀 渠 宇 宙 稳 必 须 固 杯 重 态 即 使 饮 挤 浴 桶 简 博 馆 览 技 育 究 哨 诊 律 耷 遇 咦 竖 竿 舞 痛 烦 扇 罩 牌 顾 夫 完 脖 趴 袜 匆 蜈 蚣 烂 换 搬 喝 坑 舒 集 播 茵 砍 灌 缺 栽 泳 愣 量 昆 怜 另 仿 佛 尽 并 任 何 纺 竭 规 待 醒 挣 愉 帚 抹 拖 簸 箕 玻 璃 垃 圾`
  .trim()
  .split(/\s+/);

/** @type {Record<string, { emoji: string; w: [string, string]; meaning: string; scene: string; memory: string; example: string; parts: string[] }>} */
const D = {
  橡: {
    emoji: "🌳",
    w: ["橡皮", "橡树"],
    meaning: "一种大树，橡皮擦也用它的名字。",
    scene: "🌳🧽🍃",
    memory: "木+象：像大象一样粗壮的树。",
    example: "我用橡皮擦掉写错的字。",
    parts: ["木", "象"],
  },
  枪: {
    emoji: "🔫",
    w: ["手枪", "水枪"],
    meaning: "能发射子弹或水柱的管形武器或玩具。",
    scene: "🔫💧🎯",
    memory: "木+仓：古代枪杆像木，仓里藏弹药。",
    example: "小朋友玩水枪要避开眼睛。",
    parts: ["木", "仓"],
  },
  控: {
    emoji: "🎮",
    w: ["控制", "遥控"],
    meaning: "用手或机器让东西按你的想法动。",
    scene: "🎮🕹️✋",
    memory: "扌+空：用手把局面握在掌控里。",
    example: "爸爸用遥控器换电视频道。",
    parts: ["扌", "空"],
  },
  坦: {
    emoji: "🛣️",
    w: ["坦克", "平坦"],
    meaning: "平得像桌面；也指很直率。",
    scene: "🛣️📏😊",
    memory: "土+旦：太阳升起，地面一片坦平。",
    example: "操场跑道很平坦。",
    parts: ["土", "旦"],
  },
  克: {
    emoji: "⚖️",
    w: ["千克", "克服"],
    meaning: "战胜困难；也用作重量单位。",
    scene: "⚖️🏔️💪",
    memory: "十+兄：十兄弟齐心，就能克服困难。",
    example: "我们要克服害怕，勇敢上台。",
    parts: ["十", "兄"],
  },
  航: {
    emoji: "✈️",
    w: ["航行", "航空"],
    meaning: "船或飞机在路上或天上走。",
    scene: "✈️🚢🌊",
    memory: "舟+亢：船高高昂起头向前航。",
    example: "飞机在蓝天上航行。",
    parts: ["舟", "亢"],
  },
  模: {
    emoji: "📐",
    w: ["模型", "模样"],
    meaning: "照着样子做的小样品；长相。",
    scene: "📐🧱🎨",
    memory: "木+莫：木头默默变成模具的样子。",
    example: "我用积木搭了一个飞机模型。",
    parts: ["木", "莫"],
  },
  型: {
    emoji: "🧱",
    w: ["模型", "类型"],
    meaning: "样子、款式。",
    scene: "🧱📦🔤",
    memory: "刑+土：像用土塑出固定的形状。",
    example: "这种饼干是心型的。",
    parts: ["刑", "土"],
  },
  寓: {
    emoji: "🏠",
    w: ["公寓", "寓言"],
    meaning: "住的地方；故事里藏着道理。",
    scene: "🏠📖🐇",
    memory: "宀+禺：房子里有奇遇，就是寓言。",
    example: "我们住在一套小公寓里。",
    parts: ["宀", "禺"],
  },
  则: {
    emoji: "📏",
    w: ["规则", "原则"],
    meaning: "大家都要遵守的规定。",
    scene: "📏✅🚦",
    memory: "贝+刀：古代用刀在贝壳上刻法则。",
    example: "过马路要遵守交通规则。",
    parts: ["贝", "刂"],
  },
  亡: {
    emoji: "💀",
    w: ["死亡", "逃亡"],
    meaning: "没有了、消失；也指生命结束。",
    scene: "💨🚪❌",
    memory: "亠+乚：像人躲进角落不见了。",
    example: "小鱼离开水就会死亡。",
    parts: ["亠", "乚"],
  },
  牢: {
    emoji: "🔒",
    w: ["牢房", "牢记"],
    meaning: "关人的房间；牢牢记住。",
    scene: "🔒🏛️🧠",
    memory: "宀+牛：牛被关在屋子里跑不掉。",
    example: "我把妈妈的电话牢记在心里。",
    parts: ["宀", "牛"],
  },
  圈: {
    emoji: "⭕",
    w: ["圆圈", "羊圈"],
    meaning: "圆环；也指围起来的地方。",
    scene: "⭕🐑🧵",
    memory: "囗+卷：口把东西卷成一圈。",
    example: "我在纸上画了一个圆圈。",
    parts: ["囗", "卷"],
  },
  叼: {
    emoji: "🐕",
    w: ["叼走", "叼着"],
    meaning: "用嘴紧紧夹住东西。",
    scene: "🐕🦴👄",
    memory: "口+刁：嘴巴刁住东西不松口。",
    example: "小狗叼着骨头跑回家。",
    parts: ["口", "刁"],
  },
  修: {
    emoji: "🔧",
    w: ["修理", "修路"],
    meaning: "把坏的东西弄好。",
    scene: "🔧🛠️🚧",
    memory: "亻+丨+夂：人拿工具慢慢修整。",
    example: "叔叔来家里修理水龙头。",
    parts: ["亻", "丨", "夂"],
  },
  堵: {
    emoji: "🧱",
    w: ["堵车", "堵住"],
    meaning: "把路或口塞住。",
    scene: "🚗🧱🚧",
    memory: "土+者：用土把洞口堵上。",
    example: "下雨天容易堵车。",
    parts: ["土", "者"],
  },
  悔: {
    emoji: "😔",
    w: ["后悔", "悔过"],
    meaning: "知道自己做错了，心里难过。",
    scene: "😔💭✏️",
    memory: "忄+每：心里每次都想起那件错事。",
    example: "我后悔没早点睡觉。",
    parts: ["忄", "每"],
  },
  实: {
    emoji: "✅",
    w: ["实在", "果实"],
    meaning: "真的、满满的；也指果子。",
    scene: "✅🍎📦",
    memory: "宀+头：屋里头装的是真货。",
    example: "他是一个实在的好朋友。",
    parts: ["宀", "头"],
  },
  焦: {
    emoji: "🔥",
    w: ["焦急", "焦点"],
    meaning: "心里很着急；火烧得很黑。",
    scene: "🔥😰🎯",
    memory: "隹+灬：鸟在火上烤，烤焦了。",
    example: "快迟到了，我心里很焦急。",
    parts: ["隹", "灬"],
  },
  筋: {
    emoji: "💪",
    w: ["筋骨", "脑筋"],
    meaning: "身体里拉动的带子；也指想法。",
    scene: "💪🧠🦴",
    memory: "⺮+力：竹子有韧性，像筋一样有力。",
    example: "跑步能锻炼筋骨。",
    parts: ["⺮", "力"],
  },
  喘: {
    emoji: "😮‍💨",
    w: ["喘气", "喘息"],
    meaning: "呼吸又急又大声。",
    scene: "😮‍💨🏃‍♂️💨",
    memory: "口+耑：嘴巴一端急急喷气。",
    example: "跑完步我在大口喘气。",
    parts: ["口", "耑"],
  },
  费: {
    emoji: "💰",
    w: ["费用", "浪费"],
    meaning: "花的钱；用掉太多。",
    scene: "💰🧾⏳",
    memory: "贝+弗：贝壳代表钱，弗要乱花。",
    example: "买书要花一点费用。",
    parts: ["贝", "弗"],
  },
  截: {
    emoji: "✂️",
    w: ["截断", "拦截"],
    meaning: "从中间切开；半路拦住。",
    scene: "✂️🪵🛑",
    memory: "戈+隹：像用刀戈把鸟雀半路截住。",
    example: "我用剪刀把绳子截断。",
    parts: ["戈", "隹"],
  },
  室: {
    emoji: "🚪",
    w: ["教室", "卧室"],
    meaning: "有屋顶的小房间。",
    scene: "🚪🛏️📚",
    memory: "宀+至：人走到屋子里休息。",
    example: "我们在教室里读书。",
    parts: ["宀", "至"],
  },
  而: {
    emoji: "🔗",
    w: ["而且", "然而"],
    meaning: "连接词：并且、可是。",
    scene: "🔗➕🔄",
    memory: "像胡须垂下，把话一句句连起来。",
    example: "下雨了，然而我还是去了。",
    parts: [],
  },
  幅: {
    emoji: "🖼️",
    w: ["一幅", "幅度"],
    meaning: "布或画的宽度；量词。",
    scene: "🖼️📏🧣",
    memory: "巾+畐：巾帛满满的，就是一大幅。",
    example: "墙上挂着一幅美丽的画。",
    parts: ["巾", "畐"],
  },
  审: {
    emoji: "🔍",
    w: ["审查", "审判"],
    meaning: "仔细看；法官判断对错。",
    scene: "🔍⚖️📜",
    memory: "宀+申：在屋里把理由申说清楚。",
    example: "老师审查我们的作业。",
    parts: ["宀", "申"],
  },
  肃: {
    emoji: "🫡",
    w: ["严肃", "肃静"],
    meaning: "很认真、很安静、很规矩。",
    scene: "🫡🤫🏛️",
    memory: "肀+笔画像人站得笔直。",
    example: "开会时要保持肃静。",
    parts: [],
  },
  晌: {
    emoji: "☀️",
    w: ["晌午", "半晌"],
    meaning: "中午前后的一段时间。",
    scene: "☀️🕛🍚",
    memory: "日+向：太阳向着头顶，就是晌午。",
    example: "晌午我们在食堂吃饭。",
    parts: ["日", "向"],
  },
  嘻: {
    emoji: "😄",
    w: ["嘻嘻", "嘻哈"],
    meaning: "笑的声音。",
    scene: "😄🎤🎶",
    memory: "口+喜：嘴里喜洋洋地笑出声。",
    example: "妹妹嘻嘻地笑个不停。",
    parts: ["口", "喜"],
  },
  悦: {
    emoji: "😊",
    w: ["喜悦", "悦耳"],
    meaning: "心里高兴、喜欢。",
    scene: "😊🎵💖",
    memory: "忄+兑：心里兑现了愿望就喜悦。",
    example: "小鸟的歌声很悦耳。",
    parts: ["忄", "兑"],
  },
  诲: {
    emoji: "👩‍🏫",
    w: ["教诲", "诲人不倦"],
    meaning: "耐心地教导别人。",
    scene: "👩‍🏫📖💡",
    memory: "讠+每：老师每天都用语言教你。",
    example: "我牢记老师的教诲。",
    parts: ["讠", "每"],
  },
  棚: {
    emoji: "🏚️",
    w: ["棚子", "车棚"],
    meaning: "用木或布搭的简单小屋。",
    scene: "🏚️🚲🌧️",
    memory: "木+朋：木头像朋友一样撑起棚顶。",
    example: "自行车放在车棚里。",
    parts: ["木", "朋"],
  },
  驮: {
    emoji: "🐫",
    w: ["驮运", "驮着"],
    meaning: "用背背着很重的东西。",
    scene: "🐫📦🏜️",
    memory: "马+大：大马背起大包裹。",
    example: "骆驼能驮运很多货物。",
    parts: ["马", "大"],
  },
  坊: {
    emoji: "🏘️",
    w: ["作坊", "街坊"],
    meaning: "小手工业的地方；邻居街巷。",
    scene: "🏘️🧵🍞",
    memory: "土+方：一块方方的土地上的小店。",
    example: "奶奶和街坊邻居很要好。",
    parts: ["土", "方"],
  },
  浅: {
    emoji: "🦶",
    w: ["浅水", "深浅"],
    meaning: "水不深；颜色淡。",
    scene: "🦶💧🏖️",
    memory: "氵+戋：水浅浅只剩一点点戋戋。",
    example: "小河这一段水很浅。",
    parts: ["氵", "戋"],
  },
  刚: {
    emoji: "💎",
    w: ["刚才", "刚强"],
    meaning: "硬、坚强；刚刚发生。",
    scene: "💎⚙️⏱️",
    memory: "冈+刂：山冈上刀一样硬的石头。",
    example: "我刚才看见一只蝴蝶。",
    parts: ["冈", "刂"],
  },
  淹: {
    emoji: "🌊",
    w: ["淹没", "淹水"],
    meaning: "水漫过东西。",
    scene: "🌊🏠🦺",
    memory: "氵+奄：大水把屋子奄没了。",
    example: "大雨把小路淹没了。",
    parts: ["氵", "奄"],
  },
  哩: {
    emoji: "💬",
    w: ["好哩", "哩哩啦啦"],
    meaning: "语气词，像在说“呢”“啦”。",
    scene: "💬🎵😄",
    memory: "口+里：话在嘴里转来转去。",
    example: "快走吧，好哩！",
    parts: ["口", "里"],
  },
  叹: {
    emoji: "😮‍💨",
    w: ["叹气", "感叹"],
    meaning: "把气呼出来，表示心情。",
    scene: "😮‍💨📝🌅",
    memory: "口+又：嘴里又一次发出声音。",
    example: "他看着成绩单叹了口气。",
    parts: ["口", "又"],
  },
  唉: {
    emoji: "😞",
    w: ["唉呀", "唉声叹气"],
    meaning: "表示可惜、难过或提醒。",
    scene: "😞💬🌧️",
    memory: "口+矣：嘴里说出“矣”的叹息。",
    example: "唉，我把水杯打翻了。",
    parts: ["口", "矣"],
  },
  蹄: {
    emoji: "🐎",
    w: ["马蹄", "蹄子"],
    meaning: "马、猪等动物的脚。",
    scene: "🐎👣🌾",
    memory: "⻊+帝：脚下像帝王一样稳稳落地。",
    example: "小马跑得蹄声哒哒响。",
    parts: ["⻊", "帝"],
  },
  既: {
    emoji: "✔️",
    w: ["既然", "既定"],
    meaning: "已经这样；因果关系里的“既然”。",
    scene: "✔️📅🔁",
    memory: "旡+旡：吃完转身，表示事情已完成。",
    example: "既然答应了，就要做到。",
    parts: ["旡", "旡"],
  },
  厨: {
    emoji: "🍳",
    w: ["厨房", "厨师"],
    meaning: "做饭的地方；做饭的人。",
    scene: "🍳🥘🏠",
    memory: "厂+豆+寸：厂里有豆，寸寸用心做菜。",
    example: "妈妈在厨房做晚饭。",
    parts: ["厂", "豆", "寸"],
  },
  柜: {
    emoji: "🗄️",
    w: ["柜子", "书柜"],
    meaning: "装东西的有门家具。",
    scene: "🗄️📚👕",
    memory: "木+巨：巨大的木箱能收纳。",
    example: "我把书放进书柜里。",
    parts: ["木", "巨"],
  },
  厢: {
    emoji: "🚃",
    w: ["车厢", "厢房"],
    meaning: "车或房子旁边的一间。",
    scene: "🚃🏠🪟",
    memory: "厂+相：厂房里相对的两边房间。",
    example: "我坐在火车的车厢里。",
    parts: ["厂", "相"],
  },
  商: {
    emoji: "🏪",
    w: ["商店", "商量"],
    meaning: "卖东西的地方；一起讨论。",
    scene: "🏪🛒🤝",
    memory: "亠+冏+口：在屋檐下开口谈生意。",
    example: "我们去商店买牛奶。",
    parts: ["亠", "冏", "口"],
  },
  厦: {
    emoji: "🏢",
    w: ["大厦", "高楼大厦"],
    meaning: "很高很大的楼房。",
    scene: "🏢🌆🪟",
    memory: "厂+夏：夏天一样高大的建筑。",
    example: "城市里有很多高楼大厦。",
    parts: ["厂", "夏"],
  },
  洞: {
    emoji: "🕳️",
    w: ["山洞", "洞口"],
    meaning: "中间空的地方，能穿过去。",
    scene: "🕳️🦇⛰️",
    memory: "氵+同：水把石头冲成相通的洞。",
    example: "小兔子钻进洞里。",
    parts: ["氵", "同"],
  },
  穴: {
    emoji: "🕳️",
    w: ["洞穴", "穴位"],
    meaning: "地上的坑或动物的家。",
    scene: "🕳️🐾🏔️",
    memory: "像屋顶下有个凹进去的窝。",
    example: "鼹鼠住在地下的洞穴里。",
    parts: [],
  },
  窟: {
    emoji: "⛰️",
    w: ["窟窿", "石窟"],
    meaning: "深深的洞。",
    scene: "⛰️🕳️🦇",
    memory: "穴+屈：洞里弯弯曲曲像屈服的路。",
    example: "墙上有个小窟窿。",
    parts: ["穴", "屈"],
  },
  窿: {
    emoji: "🕳️",
    w: ["窟窿", "穹窿"],
    meaning: "很深的洞或弯顶。",
    scene: "🕳️🌌🏛️",
    memory: "穴+隆：洞里隆隆像很深。",
    example: "袜子破了一个窟窿。",
    parts: ["穴", "隆"],
  },
  窖: {
    emoji: "🥔",
    w: ["地窖", "菜窖"],
    meaning: "地下的小储藏室。",
    scene: "🥔🧅🪜",
    memory: "穴+告：在洞里告诉你：这里藏菜。",
    example: "冬天把白菜放在地窖里。",
    parts: ["穴", "告"],
  },
  窄: {
    emoji: "↔️",
    w: ["狭窄", "宽窄"],
    meaning: "两边靠得很近，不宽。",
    scene: "↔️🚶🧱",
    memory: "穴+乍：洞里突然觉得很挤很窄。",
    example: "这条小巷很狭窄。",
    parts: ["穴", "乍"],
  },
  甫: {
    emoji: "👔",
    w: ["杜甫", "神甫"],
    meaning: "古代对男子的美称；也用于译名。",
    scene: "👔📜✒️",
    memory: "用字旁常作声旁，像“辅、圃”。",
    example: "我们读过诗人杜甫的诗。",
    parts: [],
  },
  泊: {
    emoji: "⚓",
    w: ["停泊", "湖泊"],
    meaning: "船停在水边；一片静水。",
    scene: "⚓🛶🏞️",
    memory: "氵+白：水面白白静静，船停泊。",
    example: "小船停泊在湖边。",
    parts: ["氵", "白"],
  },
  净: {
    emoji: "🧼",
    w: ["干净", "净水"],
    meaning: "没有脏东西。",
    scene: "🧼✨🚿",
    memory: "冫+争：像争着把东西洗争（净）了。",
    example: "我把手洗得很干净。",
    parts: ["冫", "争"],
  },
  宋: {
    emoji: "📜",
    w: ["宋朝", "宋体"],
    meaning: "古代朝代名；也用作姓。",
    scene: "📜🏯✒️",
    memory: "宀+木：屋里有木简记录历史。",
    example: "这本故事书讲到宋朝。",
    parts: ["宀", "木"],
  },
  压: {
    emoji: "🪨",
    w: ["压力", "压住"],
    meaning: "从上往下用力按住。",
    scene: "🪨📎👇",
    memory: "厂+土：厂棚下的土石往下压。",
    example: "我用书本压住被风吹起的纸。",
    parts: ["厂", "土"],
  },
  蝉: {
    emoji: "🦗",
    w: ["蝉鸣", "金蝉"],
    meaning: "夏天树上会叫的昆虫。",
    scene: "🦗🌳☀️",
    memory: "虫+单：虫子单独在树上唱歌。",
    example: "夏天，蝉在树上大声叫。",
    parts: ["虫", "单"],
  },
  响: {
    emoji: "🔔",
    w: ["响声", "响亮"],
    meaning: "发出声音；声音大。",
    scene: "🔔📣👂",
    memory: "口+向：声音向四处传开。",
    example: "上课铃响得很响亮。",
    parts: ["口", "向"],
  },
  哗: {
    emoji: "🌊",
    w: ["喧哗", "哗啦啦"],
    meaning: "吵闹的声音；水流声。",
    scene: "🌊👥📢",
    memory: "口+华：嘴里华丽地吵成一片。",
    example: "教室里不要大声喧哗。",
    parts: ["口", "华"],
  },
  慌: {
    emoji: "😰",
    w: ["慌张", "心慌"],
    meaning: "心里乱，手脚不知怎么办。",
    scene: "😰🏃💓",
    memory: "忄+荒：心里荒了，就慌张。",
    example: "找不到妈妈时我有点慌张。",
    parts: ["忄", "荒"],
  },
  针: {
    emoji: "🪡",
    w: ["针线", "打针"],
    meaning: "尖尖细细能缝衣或治病的东西。",
    scene: "🪡💉🧵",
    memory: "钅+十：金属上十字尖尖。",
    example: "护士阿姨给我打针。",
    parts: ["钅", "十"],
  },
  辨: {
    emoji: "🔎",
    w: ["分辨", "辨别"],
    meaning: "把两种东西分清楚。",
    scene: "🔎🍎🍏",
    memory: "辛+辛+讠：两边都要辛苦看清楚。",
    example: "我能辨别红苹果和青苹果。",
    parts: ["辛", "辛", "讠"],
  },
  忠: {
    emoji: "❤️",
    w: ["忠心", "忠诚"],
    meaning: "对人或国家很真心。",
    scene: "❤️🛡️🤝",
    memory: "中+心：把心放在正中间不偏。",
    example: "小狗对主人很忠诚。",
    parts: ["中", "心"],
  },
  导: {
    emoji: "🧭",
    w: ["导游", "引导"],
    meaning: "带路；让人明白怎么做。",
    scene: "🧭🗺️👣",
    memory: "巳+寸：寸寸指路，像导游。",
    example: "导游带我们参观博物馆。",
    parts: ["巳", "寸"],
  },
  盏: {
    emoji: "🍵",
    w: ["灯盏", "一盏"],
    meaning: "小杯子；油灯的小碟。",
    scene: "🍵🕯️✨",
    memory: "戋+皿：浅浅的器皿装灯油。",
    example: "奶奶点了一盏小油灯。",
    parts: ["戋", "皿"],
  },
  永: {
    emoji: "♾️",
    w: ["永远", "永久"],
    meaning: "一直不变，很长时间。",
    scene: "♾️💧🌊",
    memory: "像水一直流，不停歇。",
    example: "我们是永远的好朋友。",
    parts: [],
  },
  闯: {
    emoji: "🚪",
    w: ["闯祸", "闯荡"],
    meaning: "猛冲进去；到外面去闯。",
    scene: "🚪💥🌍",
    memory: "门+马：马冲进门里，很莽撞。",
    example: "乱跑容易闯祸。",
    parts: ["门", "马"],
  },
  碰: {
    emoji: "💥",
    w: ["碰到", "碰撞"],
    meaning: "两个东西撞在一起。",
    scene: "💥🚗🚧",
    memory: "石+並：两块石头并排撞上。",
    example: "我不小心碰到桌角。",
    parts: ["石", "並"],
  },
  稠: {
    emoji: "🍯",
    w: ["稠密", "黏稠"],
    meaning: "很浓、很挤，不稀。",
    scene: "🍯🐝📚",
    memory: "禾+周：粥周周稠稠像蜂蜜。",
    example: "蜂蜜黏稠黏的。",
    parts: ["禾", "周"],
  },
  稀: {
    emoji: "🥣",
    w: ["稀薄", "稀少"],
    meaning: "很淡、很少。",
    scene: "🥣☁️🌾",
    memory: "禾+希：禾苗稀稀拉拉很少。",
    example: "清晨空气很稀薄。",
    parts: ["禾", "希"],
  },
  渠: {
    emoji: "🌊",
    w: ["水渠", "渠道"],
    meaning: "人工挖的水道；做事的途径。",
    scene: "🌊🚜🌾",
    memory: "氵+巨：巨大的水沟把水引来。",
    example: "田边有一条小水渠。",
    parts: ["氵", "巨"],
  },
  宇: {
    emoji: "🌌",
    w: ["宇宙", "楼宇"],
    meaning: "天空、空间；高楼。",
    scene: "🌌🏙️⭐",
    memory: "宀+于：屋顶之下的一切空间。",
    example: "宇航员飞到宇宙里。",
    parts: ["宀", "于"],
  },
  宙: {
    emoji: "🪐",
    w: ["宇宙", "宙斯"],
    meaning: "很长的时间；和宇一起指天地万物。",
    scene: "🪐⏳🌌",
    memory: "宀+由：时间在屋里由来很久。",
    example: "宇宙里有很多星星。",
    parts: ["宀", "由"],
  },
  稳: {
    emoji: "⚖️",
    w: ["稳定", "站稳"],
    meaning: "不摇晃、很牢靠。",
    scene: "⚖️🧍🪨",
    memory: "禾+急：禾穗沉甸甸，站得稳稳不急晃。",
    example: "爸爸扶着我，我站稳了。",
    parts: ["禾", "急"],
  },
  必: {
    emoji: "✅",
    w: ["必须", "必要"],
    meaning: "一定要这样。",
    scene: "✅📌🎯",
    memory: "心加撇：心里认定非做不可。",
    example: "饭前必须洗手。",
    parts: [],
  },
  须: {
    emoji: "🧔",
    w: ["必须", "胡须"],
    meaning: "一定要；脸上的毛。",
    scene: "🧔✅📜",
    memory: "彡+页：页边像胡须飘动。",
    example: "过马路必须看红绿灯。",
    parts: ["彡", "页"],
  },
  固: {
    emoji: "🔒",
    w: ["坚固", "固定"],
    meaning: "很结实，不容易动。",
    scene: "🔒🧱🪨",
    memory: "囗+古：把古老的东西围在口里很牢。",
    example: "这座桥很坚固。",
    parts: ["囗", "古"],
  },
  杯: {
    emoji: "🥤",
    w: ["水杯", "杯子"],
    meaning: "用来喝水的器皿。",
    scene: "🥤🧃🍵",
    memory: "木+不：古代木杯装不满也要喝。",
    example: "我用杯子喝牛奶。",
    parts: ["木", "不"],
  },
  重: {
    emoji: "⚖️",
    w: ["重量", "重要"],
    meaning: "沉；很要紧。",
    scene: "⚖️📦⭐",
    memory: "千里：千里挑一，所以很重要。",
    example: "书包太重了，我背不动。",
    parts: ["千", "里"],
  },
  态: {
    emoji: "🙂",
    w: ["态度", "状态"],
    meaning: "样子、心情的表现。",
    scene: "🙂💭📊",
    memory: "太+心：心里太大就会表现在态度上。",
    example: "他对人有礼貌的态度很好。",
    parts: ["太", "心"],
  },
  即: {
    emoji: "➡️",
    w: ["即使", "立即"],
    meaning: "马上；就算。",
    scene: "➡️⏱️✅",
    memory: "卩+艮：靠近节（卩）艮快就到。",
    example: "铃一响，我们立即排队。",
    parts: ["卩", "艮"],
  },
  使: {
    emoji: "🤝",
    w: ["使用", "即使"],
    meaning: "让人去做；用工具。",
    scene: "🤝🛠️👥",
    memory: "亻+吏：人当小吏去办事。",
    example: "我会使用剪刀剪纸。",
    parts: ["亻", "吏"],
  },
  饮: {
    emoji: "🥤",
    w: ["饮水", "饮料"],
    meaning: "喝液体。",
    scene: "🥤💧🧃",
    memory: "饣+欠：吃了还欠一口水，所以要饮。",
    example: "运动后要多饮水。",
    parts: ["饣", "欠"],
  },
  挤: {
    emoji: "🚌",
    w: ["拥挤", "挤奶"],
    meaning: "很多人靠在一起；用力压出。",
    scene: "🚌👥🥛",
    memory: "扌+齐：用手把大家齐到一块。",
    example: "公交车上人很拥挤。",
    parts: ["扌", "齐"],
  },
  浴: {
    emoji: "🛁",
    w: ["沐浴", "浴室"],
    meaning: "用水洗身体。",
    scene: "🛁🧼🚿",
    memory: "氵+谷：山谷里的清水洗澡。",
    example: "我在浴室里沐浴。",
    parts: ["氵", "谷"],
  },
  桶: {
    emoji: "🪣",
    w: ["水桶", "木桶"],
    meaning: "圆筒形容器，能装水。",
    scene: "🪣💧🧹",
    memory: "木+甬：木头像甬道一样圆筒。",
    example: "奶奶用木桶提水。",
    parts: ["木", "甬"],
  },
  简: {
    emoji: "📄",
    w: ["简单", "竹简"],
    meaning: "不复杂；古代写字的竹片。",
    scene: "📄✏️🎋",
    memory: "⺮+间：竹片间隔排列成简册。",
    example: "这道题很简单。",
    parts: ["⺮", "间"],
  },
  博: {
    emoji: "📚",
    w: ["博士", "博学"],
    meaning: "知道很多；学问大。",
    scene: "📚🎓🌍",
    memory: "十+尃：十样尃广的知识都懂。",
    example: "爷爷读书很多，很博学。",
    parts: ["十", "尃"],
  },
  馆: {
    emoji: "🏛️",
    w: ["图书馆", "饭馆"],
    meaning: "公共活动场所或吃饭的地方。",
    scene: "🏛️📖🍜",
    memory: "饣+官：官方或大家去的用餐学习处。",
    example: "周末我去图书馆看书。",
    parts: ["饣", "官"],
  },
  览: {
    emoji: "👀",
    w: ["浏览", "展览"],
    meaning: "看一看；把东西摆出来给大家看。",
    scene: "👀🖼️🎪",
    memory: "监+见：监督着亲眼看见。",
    example: "我们在博物馆展览恐龙化石。",
    parts: ["监", "见"],
  },
  技: {
    emoji: "🔧",
    w: ["技术", "技巧"],
    meaning: "做事的本领。",
    scene: "🔧⚙️🎯",
    memory: "扌+支：用手支持完成技巧。",
    example: "他踢球技术很好。",
    parts: ["扌", "支"],
  },
  育: {
    emoji: "🌱",
    w: ["教育", "体育"],
    meaning: "养大、教导；锻炼身体。",
    scene: "🌱👩‍🏫⚽",
    memory: "云+月+肉：像云月下滋养生命成长。",
    example: "老师教育我们要诚实。",
    parts: ["云", "月", "肉"],
  },
  究: {
    emoji: "🔬",
    w: ["研究", "究竟"],
    meaning: "追问到底；探索原因。",
    scene: "🔬🧪❓",
    memory: "穴+九：洞里数到九，要追究到底。",
    example: "科学家研究星星。",
    parts: ["穴", "九"],
  },
  哨: {
    emoji: "👮",
    w: ["哨兵", "口哨"],
    meaning: "站岗的人；吹的小声信号。",
    scene: "👮🎺🏰",
    memory: "口+肖：嘴里吹出肖似鸟叫的哨声。",
    example: "体育老师吹响口哨。",
    parts: ["口", "肖"],
  },
  诊: {
    emoji: "🩺",
    w: ["诊所", "诊断"],
    meaning: "医生看病问情况。",
    scene: "🩺🏥💊",
    memory: "讠+珍：用语言珍惜地询问病情。",
    example: "医生给我诊断感冒。",
    parts: ["讠", "珍"],
  },
  律: {
    emoji: "📜",
    w: ["法律", "规律"],
    meaning: "大家遵守的规则；重复出现的方式。",
    scene: "📜⚖️🔁",
    memory: "彳+聿：行走要按聿笔写下的规矩。",
    example: "我们要遵守交通规则。",
    parts: ["彳", "聿"],
  },
  耷: {
    emoji: "🐘",
    w: ["耷拉", "蔫耷耷"],
    meaning: "软软地垂下来。",
    scene: "🐘👂🍃",
    memory: "大+耳：大大的耳朵垂下来。",
    example: "小狗累了，耳朵耷拉着。",
    parts: ["大", "耳"],
  },
  遇: {
    emoji: "🤝",
    w: ["遇到", "相遇"],
    meaning: "碰见、碰到。",
    scene: "🤝🚶🌈",
    memory: "辶+禺：走在路上有奇遇。",
    example: "我在公园遇到同学。",
    parts: ["辶", "禺"],
  },
  咦: {
    emoji: "😲",
    w: ["咦呀", "咦咦"],
    meaning: "表示惊讶或奇怪的声音。",
    scene: "😲❓💬",
    memory: "口+夷：嘴里发出夷然的惊声。",
    example: "咦，我的橡皮不见了！",
    parts: ["口", "夷"],
  },
  竖: {
    emoji: "📏",
    w: ["竖立", "横竖"],
    meaning: "直着向上，跟横相对。",
    scene: "📏⬆️🪵",
    memory: "立+臣：像臣子站得笔直。",
    example: "把竹竿竖立在墙角。",
    parts: ["立", "臣"],
  },
  竿: {
    emoji: "🎣",
    w: ["竹竿", "鱼竿"],
    meaning: "细长的竹子杆。",
    scene: "🎣🎋🌊",
    memory: "⺮+干：竹子干成一根竿。",
    example: "爷爷用鱼竿钓鱼。",
    parts: ["⺮", "干"],
  },
  舞: {
    emoji: "💃",
    w: ["跳舞", "舞台"],
    meaning: "跟着音乐扭动身体表演。",
    scene: "💃🎶🎭",
    memory: "舛+舛：两只脚左右摆动像跳舞。",
    example: "我们在舞台上跳舞。",
    parts: ["舛", "夕"],
  },
  痛: {
    emoji: "😣",
    w: ["疼痛", "头痛"],
    meaning: "身体不舒服的难受感觉。",
    scene: "😣💊🩹",
    memory: "疒+甬：病像甬道一样通到全身。",
    example: "我摔了一跤，膝盖很痛。",
    parts: ["疒", "甬"],
  },
  烦: {
    emoji: "😫",
    w: ["烦恼", "麻烦"],
    meaning: "心里乱、觉得累。",
    scene: "😫📋🌀",
    memory: "火+页：心里着火翻页也烦。",
    example: "作业太多让我很烦恼。",
    parts: ["火", "页"],
  },
  扇: {
    emoji: "🪭",
    w: ["扇子", "风扇"],
    meaning: "用来扇风降温的东西。",
    scene: "🪭💨❄️",
    memory: "户+羽：门户外羽毛轻轻扇动。",
    example: "夏天奶奶摇扇子乘凉。",
    parts: ["户", "羽"],
  },
  罩: {
    emoji: "🫙",
    w: ["口罩", "灯罩"],
    meaning: "盖在外面保护或遮住。",
    scene: "🫙😷💡",
    memory: "罒+卓：网罩卓然盖在上面。",
    example: "出门要戴口罩。",
    parts: ["罒", "卓"],
  },
  牌: {
    emoji: "🃏",
    w: ["牌子", "路牌"],
    meaning: "写着字或图形的板子。",
    scene: "🃏🪧🏷️",
    memory: "片+卑：薄片上写着卑微到清楚的说明。",
    example: "路牌告诉我们怎么走。",
    parts: ["片", "卑"],
  },
  顾: {
    emoji: "👀",
    w: ["照顾", "回顾"],
    meaning: "回头看；关心别人。",
    scene: "👀🔄🤗",
    memory: "厄+页：转头看页边的信息。",
    example: "老师照顾每一位同学。",
    parts: ["厄", "页"],
  },
  夫: {
    emoji: "👨",
    w: ["丈夫", "农夫"],
    meaning: "成年男子；某些职业里的人。",
    scene: "👨🌾🔨",
    memory: "大上加一横：大人顶天立地。",
    example: "农夫在田里种地。",
    parts: [],
  },
  完: {
    emoji: "✅",
    w: ["完成", "完美"],
    meaning: "没有缺少；做好了。",
    scene: "✅🧩🌟",
    memory: "宀+元：屋里的元首事都做完。",
    example: "我把作业写完了。",
    parts: ["宀", "元"],
  },
  脖: {
    emoji: "🧣",
    w: ["脖子", "围脖"],
    meaning: "头和身体相连的部分。",
    scene: "🧣👤🔗",
    memory: "月+孛：肉肉的部位学名叫脖。",
    example: "天冷我把围巾围在脖子上。",
    parts: ["月", "孛"],
  },
  趴: {
    emoji: "🐸",
    w: ["趴下", "趴着"],
    meaning: "胸腹朝下贴着地面或桌子。",
    scene: "🐸📖🛏️",
    memory: "足+八：脚八字形趴开在地上。",
    example: "小狗趴在地上睡觉。",
    parts: ["足", "八"],
  },
  袜: {
    emoji: "🧦",
    w: ["袜子", "鞋袜"],
    meaning: "穿在脚上的软布套。",
    scene: "🧦👟❄️",
    memory: "衤+末：衣服穿到脚末就是袜。",
    example: "我把袜子洗得干干净净。",
    parts: ["衤", "末"],
  },
  匆: {
    emoji: "🏃",
    w: ["匆忙", "匆匆"],
    meaning: "很着急、很快。",
    scene: "🏃⏰💨",
    memory: "勹+丶+丿：包起东西就跑，很匆忙。",
    example: "我匆忙赶到学校。",
    parts: ["勹", "丶"],
  },
  蜈: {
    emoji: "🐛",
    w: ["蜈蚣", "地蜈蚣"],
    meaning: "一种很多脚的虫子，常和蚣连用。",
    scene: "🐛👣🌿",
    memory: "虫+吴：吴地多见的虫子。",
    example: "石头下爬出一条蜈蚣。",
    parts: ["虫", "吴"],
  },
  蚣: {
    emoji: "🐛",
    w: ["蜈蚣", "大蜈蚣"],
    meaning: "多脚虫名字的一部分。",
    scene: "🐛🔗🌿",
    memory: "虫+公：很多脚像公的排队。",
    example: "不要用手抓蜈蚣。",
    parts: ["虫", "公"],
  },
  烂: {
    emoji: "🍎",
    w: ["破烂", "腐烂"],
    meaning: "坏掉、变软发臭。",
    scene: "🍎🪰🗑️",
    memory: "火+兰：像兰花被火烤烂了。",
    example: "苹果放久了会腐烂。",
    parts: ["火", "兰"],
  },
  换: {
    emoji: "🔄",
    w: ["交换", "更换"],
    meaning: "拿这个换那个。",
    scene: "🔄👕🧢",
    memory: "扌+奂：用手换来焕新的东西。",
    example: "我和朋友交换贴纸。",
    parts: ["扌", "奂"],
  },
  搬: {
    emoji: "📦",
    w: ["搬家", "搬运"],
    meaning: "把重东西移到别处。",
    scene: "📦🚚🏠",
    memory: "扌+般：用手般运家具。",
    example: "爸爸用车搬运箱子。",
    parts: ["扌", "般"],
  },
  喝: {
    emoji: "🥤",
    w: ["喝水", "喝彩"],
    meaning: "把液体咽下去；大声叫好。",
    scene: "🥤👏📣",
    memory: "口+曷：口里曷求一口水。",
    example: "运动后要多喝水。",
    parts: ["口", "曷"],
  },
  坑: {
    emoji: "🕳️",
    w: ["水坑", "土坑"],
    meaning: "地面凹下去的一块。",
    scene: "🕳️💧🥾",
    memory: "土+亢：土高高挖下去成坑。",
    example: "雨后路上有一个水坑。",
    parts: ["土", "亢"],
  },
  舒: {
    emoji: "😌",
    w: ["舒服", "舒适"],
    meaning: "身体轻松、心里愉快。",
    scene: "😌🛋️☁️",
    memory: "舍+予：舍得给予自己休息就舒服。",
    example: "躺在沙发上很舒服。",
    parts: ["舍", "予"],
  },
  集: {
    emoji: "📚",
    w: ["集合", "收集"],
    meaning: "聚在一起；把东西找来放一起。",
    scene: "📚👥🧺",
    memory: "隹+木：鸟落在树上成群聚集。",
    example: "下课铃响，大家到操场集合。",
    parts: ["隹", "木"],
  },
  播: {
    emoji: "📻",
    w: ["广播", "播种"],
    meaning: "声音传出去；把种子撒到土里。",
    scene: "📻🌾📡",
    memory: "扌+番：用手把种子三番五次撒开。",
    example: "爷爷在田里播种玉米。",
    parts: ["扌", "番"],
  },
  茵: {
    emoji: "🌿",
    w: ["绿茵", "茵茵"],
    meaning: "像垫子一样软软的草。",
    scene: "🌿⚽🏞️",
    memory: "艹+因：草因为茂盛像绿毯。",
    example: "足球场上有一片绿茵。",
    parts: ["艹", "因"],
  },
  砍: {
    emoji: "🪓",
    w: ["砍柴", "砍伐"],
    meaning: "用刀斧把树或东西弄断。",
    scene: "🪓🌲🪵",
    memory: "石+欠：石器欠缺了边就是砍。",
    example: "工人砍伐枯树保证安全。",
    parts: ["石", "欠"],
  },
  灌: {
    emoji: "💧",
    w: ["灌水", "灌溉"],
    meaning: "把水倒进去；给庄稼浇水。",
    scene: "💧🌾🚿",
    memory: "氵+雚：很多水灌进田里。",
    example: "农民用水渠灌溉稻田。",
    parts: ["氵", "雚"],
  },
  缺: {
    emoji: "🧩",
    w: ["缺少", "缺口"],
    meaning: "不够、破了口子。",
    scene: "🧩❌🍽️",
    memory: "缶+夬：瓦缶裂出一道夬口。",
    example: "拼图缺了一块就不完整。",
    parts: ["缶", "夬"],
  },
  栽: {
    emoji: "🌱",
    w: ["栽树", "栽培"],
    meaning: "把植物种进土里。",
    scene: "🌱🕳️🪴",
    memory: "木+戈+土：用戈在土里栽木。",
    example: "春天我们栽树绿化校园。",
    parts: ["木", "戈", "土"],
  },
  泳: {
    emoji: "🏊",
    w: ["游泳", "蛙泳"],
    meaning: "在水里用手脚划动前进。",
    scene: "🏊💦🥽",
    memory: "氵+永：在水里永远前进。",
    example: "夏天我喜欢去游泳。",
    parts: ["氵", "永"],
  },
  愣: {
    emoji: "😳",
    w: ["发愣", "愣住"],
    meaning: "一时呆住，不知道反应。",
    scene: "😳⏸️❓",
    memory: "忄+囗+方：心里被框住，方寸乱了。",
    example: "听到好消息，我愣住了。",
    parts: ["忄", "囗", "方"],
  },
  量: {
    emoji: "📏",
    w: ["测量", "重量"],
    meaning: "用工具看多少、轻重、长短。",
    scene: "📏⚖️📐",
    memory: "日+一+里：日日里都要量一量。",
    example: "用量尺测量桌子的长度。",
    parts: ["日", "一", "里"],
  },
  昆: {
    emoji: "🦗",
    w: ["昆虫", "昆明"],
    meaning: "很多腿的虫子总称；也用于地名。",
    scene: "🦗🌿🗺️",
    memory: "日+比：日日比肩而出的小虫。",
    example: "蝴蝶是一种昆虫。",
    parts: ["日", "比"],
  },
  怜: {
    emoji: "🥺",
    w: ["可怜", "怜爱"],
    meaning: "心里同情、疼爱。",
    scene: "🥺💖🐱",
    memory: "忄+令：心里下令要温柔对待。",
    example: "我怜爱那只流浪小猫。",
    parts: ["忄", "令"],
  },
  另: {
    emoji: "➕",
    w: ["另外", "另一个"],
    meaning: "别的、不是这个。",
    scene: "➕🔄📎",
    memory: "口+力：用口另说一份力气的事。",
    example: "我吃了一个苹果，另带一个回家。",
    parts: ["口", "力"],
  },
  仿: {
    emoji: "🪞",
    w: ["仿佛", "模仿"],
    meaning: "照着样子学；好像。",
    scene: "🪞🎭✏️",
    memory: "亻+方：人照着方的模板仿写。",
    example: "我喜欢模仿小鸟叫。",
    parts: ["亻", "方"],
  },
  佛: {
    emoji: "🙏",
    w: ["仿佛", "佛像"],
    meaning: "好像；也指佛教里的圣人像。",
    scene: "🙏🌫️🏯",
    memory: "亻+弗：人像弗（不）动，静静打坐。",
    example: "雾大得仿佛看不见路。",
    parts: ["亻", "弗"],
  },
  尽: {
    emoji: "🏁",
    w: ["尽力", "用尽"],
    meaning: "用完、做到最好。",
    scene: "🏁💪🧃",
    memory: "尸+尺+丶：量到尽头为止。",
    example: "我会尽力把画画好。",
    parts: ["尸", "尺"],
  },
  并: {
    emoji: "🔗",
    w: ["并且", "合并"],
    meaning: "合在一起；而且。",
    scene: "🔗➕🤝",
    memory: "像两个人并排站在一起。",
    example: "我喜欢唱歌，并且喜欢跳舞。",
    parts: [],
  },
  任: {
    emoji: "🧑‍💼",
    w: ["任何", "任务"],
    meaning: "随便哪个；交给你的工作。",
    scene: "🧑‍💼📋✅",
    memory: "亻+壬：人承担壬重的责任。",
    example: "你可以选任何一本书。",
    parts: ["亻", "壬"],
  },
  何: {
    emoji: "❓",
    w: ["任何", "为何"],
    meaning: "什么、为什么、哪里。",
    scene: "❓🌍💬",
    memory: "亻+可：人可以问“可是什么”。",
    example: "你为何迟到？",
    parts: ["亻", "可"],
  },
  纺: {
    emoji: "🧵",
    w: ["纺织", "纺纱"],
    meaning: "把棉麻捻成线。",
    scene: "🧵🪡🏭",
    memory: "纟+方：丝线纺成方方正正的布。",
    example: "奶奶会纺纱织布。",
    parts: ["纟", "方"],
  },
  竭: {
    emoji: "🔋",
    w: ["竭力", "枯竭"],
    meaning: "用尽；没有了。",
    scene: "🔋📉🏜️",
    memory: "立+曷：站立到曷尽也要坚持。",
    example: "他竭力把箱子搬上楼。",
    parts: ["立", "曷"],
  },
  规: {
    emoji: "📐",
    w: ["规则", "圆规"],
    meaning: "画圆的工具；大家遵守的规矩。",
    scene: "📐⭕📜",
    memory: "夫+见：大丈夫见到规矩要遵守。",
    example: "我们用圆规画圆。",
    parts: ["夫", "见"],
  },
  待: {
    emoji: "⏳",
    w: ["等待", "对待"],
    meaning: "等着；对人用什么态度。",
    scene: "⏳🚪🤝",
    memory: "彳+寺：在路上到寺前也要等待。",
    example: "我在门口等待妈妈。",
    parts: ["彳", "寺"],
  },
  醒: {
    emoji: "☀️",
    w: ["醒来", "清醒"],
    meaning: "从睡梦里出来；头脑清楚。",
    scene: "☀️😊☕",
    memory: "酉+星：酒醒后看见星星天亮。",
    example: "早上闹钟一响我就醒来。",
    parts: ["酉", "星"],
  },
  挣: {
    emoji: "💪",
    w: ["挣扎", "挣钱"],
    meaning: "用力摆脱；劳动换来钱。",
    scene: "💪💰🪢",
    memory: "扌+争：用手争着摆脱绳子。",
    example: "小鱼在水里挣扎。",
    parts: ["扌", "争"],
  },
  愉: {
    emoji: "😄",
    w: ["愉快", "愉悦"],
    meaning: "心里轻松快乐。",
    scene: "😄🎈🎉",
    memory: "忄+俞：心里愈合了伤口就愉快。",
    example: "春游那天我们玩得很愉快。",
    parts: ["忄", "俞"],
  },
  帚: {
    emoji: "🧹",
    w: ["扫帚", "笤帚"],
    meaning: "扫地用的工具。",
    scene: "🧹🍂🏠",
    memory: "彐+巾：拿着巾帕扫彐角。",
    example: "我用扫帚把落叶扫干净。",
    parts: ["彐", "巾"],
  },
  抹: {
    emoji: "🧽",
    w: ["抹布", "涂抹"],
    meaning: "轻轻擦；把东西涂开。",
    scene: "🧽🎨🪟",
    memory: "扌+末：用手在末尾擦一抹。",
    example: "我用抹布擦桌子。",
    parts: ["扌", "末"],
  },
  拖: {
    emoji: "🛷",
    w: ["拖把", "拖延"],
    meaning: "拉着走；做事慢吞吞。",
    scene: "🛷🧹⏳",
    memory: "扌+也：用手也把东西拖走。",
    example: "我用拖把拖地。",
    parts: ["扌", "也"],
  },
  簸: {
    emoji: "🌾",
    w: ["簸箕", "颠簸"],
    meaning: "扬米去糠的工具；上下晃。",
    scene: "🌾🧺🚗",
    memory: "⺮+皮：竹皮编成簸箕扬谷皮。",
    example: "奶奶用簸箕筛豆子。",
    parts: ["⺮", "皮"],
  },
  箕: {
    emoji: "🧺",
    w: ["簸箕", "箕踞"],
    meaning: "簸粮食的器具；像畚箕的形状。",
    scene: "🧺🌾🪵",
    memory: "⺮+其：竹编的其形器具。",
    example: "他把垃圾扫进簸箕里。",
    parts: ["⺮", "其"],
  },
  玻: {
    emoji: "🪟",
    w: ["玻璃", "玻璃钢"],
    meaning: "透明硬硬的一种材料（常与璃连用）。",
    scene: "🪟✨🏢",
    memory: "王+皮：像玉一样光滑的皮面。",
    example: "窗户是玻璃做的。",
    parts: ["王", "皮"],
  },
  璃: {
    emoji: "🪟",
    w: ["玻璃", "琉璃"],
    meaning: "透明材料名字的一部分。",
    scene: "🪟🌈🏺",
    memory: "王+离：像玉离开杂质后透亮。",
    example: "琉璃瓦在阳光下闪闪亮。",
    parts: ["王", "离"],
  },
  垃: {
    emoji: "🗑️",
    w: ["垃圾", "垃圾桶"],
    meaning: "不要的东西（常与圾连用）。",
    scene: "🗑️🍌📦",
    memory: "土+立：土堆上立着不要的东西。",
    example: "把果皮扔进垃圾桶。",
    parts: ["土", "立"],
  },
  圾: {
    emoji: "🗑️",
    w: ["垃圾", "垃圾箱"],
    meaning: "脏东西名字的一部分。",
    scene: "🗑️♻️🚮",
    memory: "土+及：土堆上及时清走。",
    example: "公园里有垃圾箱。",
    parts: ["土", "及"],
  },
};

function esc(str) {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function highlightIndex(word, ch) {
  const idx = [...word].indexOf(ch);
  if (idx < 0) throw new Error(`char ${ch} not in word ${word}`);
  return idx;
}

const missing = chars.filter((c) => !D[c]);
if (missing.length) {
  console.error("Missing:", missing.join(""));
  process.exit(1);
}

let out = `export const CHAR_DICT_P2 = {\n  // entries\n`;
for (const ch of chars) {
  const d = D[ch];
  const w1 = d.w[0];
  const w2 = d.w[1];
  const h1 = highlightIndex(w1, ch);
  const h2 = highlightIndex(w2, ch);
  const parts = d.parts.map((p) => `"${esc(p)}"`).join(", ");
  out += `  "${ch}": {\n`;
  out += `    emoji: "${esc(d.emoji)}",\n`;
  out += `    words: [{ word: "${esc(w1)}", highlight: ${h1} }, { word: "${esc(w2)}", highlight: ${h2} }],\n`;
  out += `    meaning: "${esc(d.meaning)}",\n`;
  out += `    scene: "${esc(d.scene)}",\n`;
  out += `    memory: "${esc(d.memory)}",\n`;
  out += `    example: "${esc(d.example)}",\n`;
  out += `    parts: [${parts}]\n`;
  out += `  },\n`;
}
out += `};\n`;

const outPath = path.join(root, "lib", "_charDict_p2.js");
fs.writeFileSync(outPath, out, "utf8");
console.log("Wrote", outPath, "entries", chars.length);
